#!/bin/bash
DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
echo $DIR

link(){
    if [[ -e $HOME/$1 ]]; then
        if [[ $(diff -q $DIR/$1 $HOME/$1) ]]; then
            cp $HOME/$1 $HOME/$1.old
            echo "moved old $1"
        else
            echo "didnt move $1, file is same, just deleting instead"
        fi
        rm $HOME/$1
    fi
    ln -s $DIR/$1 $HOME/$1
    echo "Linked $1"
}

linkConfig(){
    mkdir -p "$HOME/.config"

    FILE="$HOME/.config/$1"
    if [[ -e "$FILE" ]]; then
        if [[ -L "$FILE" ]]; then
            echo "Deleting symbolic link $FILE"
            rm $FILE
        else
            cp -r "$FILE" "$FILE.old"
            echo "moved old config $1: created $FILE.old"
        fi
    fi
    ln -s $DIR/.config/$1 $FILE
    echo "ln -s $DIR/.config/$1 $FILE"
}

buildRust(){
    cd $DIR/$1
    cargo install --path .
}

link .gitconfig
link .tmux.conf
link .vimrc
link .xprofile
link .xprofile.fish

for file in "./.config/"/*; do
    linkConfig $(basename "$file")
done

buildRust daily
buildRust awsctx
buildRust macros
buildRust binder

if [[ -s $ZSH ]]; then
    link .zshrc
    rm $HOME/.oh-my-zsh/custom/themes/john.zsh-theme
    ln -s $DIR/john.zsh-theme $HOME/.oh-my-zsh/custom/themes/john.zsh-theme
elif [[ -s $BASH ]]; then
    link .bashrc
fi
