#!/usr/bin/env bash

which crontab >/dev/null
if [[ $? == 0 ]]; then
    crontab -l > ./crontabs/$(cat /etc/hostname).cron
fi

git adl
git ss

read -p "Are you sure? " -n 1 -r
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 1
fi

git cim "Modified files"
