#!/bin/bash

if [ -z $1 ]; then
    echo "Enter battery device as argument"
    echo
    exit 1;
fi

source /sys/class/power_supply/$1/uevent

STATUS=$POWER_SUPPLY_STATUS
PCT=$POWER_SUPPLY_CAPACITY

B0=
B1=
B2=
B3=
B4=
B6=

if [[ $PCT -gt 95 ]]; then
    B=$B4
elif [[ $PCT -gt 75 ]]; then
    B=$B3
elif [[ $PCT -gt 50 ]]; then
    B=$B2
elif [[ $PCT -gt 25 ]]; then
    B=$B1
elif [[ $PCT -gt 0 ]]; then
    B=$B0
fi

if [ $STATUS == "Charging" ]; then
    if [ $PCT -eq "100" ]; then
        STATUS=$B6
    else
        STATUS=""
    fi
elif [ $STATUS == "Discharging" ]; then
    STATUS=`echo "scale=2; $POWER_SUPPLY_CHARGE_NOW/$POWER_SUPPLY_CURRENT_NOW" | bc`
    STATUS=${STATUS}H
fi

if [ $PCT -ne "-1" ]; then
    PCT=$PCT%
else
    PCT=""
fi

echo $B $PCT $STATUS
