#!/bin/bash

DIR="/sys/class/backlight/$1/"

BRIGHTNESSMAX=`cat $DIR/max_brightness`
BRIGHTNESS=`cat $DIR/brightness`

if [[ $2 != "get" ]]; then

    BRIGHTNESS=$(($BRIGHTNESS + $2))

    if [[ $BRIGHTNESS -gt $BRIGHTNESSMAX ]]; then
        BRIGHTNESS=$BRIGHTNESSMAX
    elif [[ $BRIGHTNESS -lt 50 ]]; then
        BRIGHTNESS=50
    fi

    echo "echo $BRIGHTNESS > $DIR/brightness" | sudo bash

    pkill -RTMIN+3 i3blocks
else
    echo "scale=0; ($BRIGHTNESS * 100)/$BRIGHTNESSMAX" | bc
fi
