#!/bin/bash

CPU=$(cat /proc/loadavg | awk '{printf("%3.0f", $1 * 100 / 4)}')
CPUINT=${CPU%.*}

COLOR="#CCCCCC"
if [[ $CPUINT -gt "30" ]]; then
    COLOR="#CCCC33"
elif [[ $CPUINT -gt "60" ]]; then
    COLOR="#CC3333"
elif [[ $CPUINT -gt "90" ]]; then
    COLOR="#FF0000"
fi

echo $CPU%
echo $CPU%
echo $COLOR
