# Shared SSH authorized keys for root
#
# Imported by all Hetzner host configs (servers, agents, home-pi).
# Eliminates the `users.users.root.openssh.authorizedKeys.keys = sshKeys`
# duplication across 7 files.
{ sshKeys, ... }: {
  users.users.root.openssh.authorizedKeys.keys = sshKeys;
  services.openssh.enable = true;

  # agenix identity — uses the SSH host key
  # Host key is generated by sshd-keygen.service on first boot
  age.identityPaths = ["/etc/ssh/ssh_host_ed25519_key"];
}
