# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  pkgs,
  ...
}: let

  ps2avr_rgb = pkgs.writers.writePython3Bin "ps2avr-rgb"
    { libraries = [ ]; }
    ''
    """Control RGB on ps2avrGB (winkeyless.kr) macropad via USB.

    Usage: ps2avr-rgb off | on | color RRGGBB | brightness N |
           rainbow [fade|static|flow|immediate|sequential] | mode N
    """
    import ctypes
    import fcntl
    import os
    import sys
    USBDEVFS_CONTROL = 0xc0185500

    # Option indexes from ps2avrGB firmware
    OPT_MODE = 0x20
    OPT_BRIGHTNESS = 0x40
    OPT_COLOR1 = 0x11
    OPT_COLOR2 = 0x12
    OPT_COLOR3 = 0x13
    OPT_RAINBOW = 0x10
    OPT_RAINBOW_INIT = 0x1F
    OPT_FADE_TYPE = 0x23

    # Mode values
    MODE_OFF = 0
    MODE_RAINBOW = 1
    MODE_COLOR1 = 2
    MODE_COLOR2 = 3
    MODE_COLOR3 = 4

    # Fade types
    FADE_FADING = 0
    FADE_IMMEDIATE = 1
    FADE_SEQUENTIAL = 2
    FADE_STATIC = 3
    FADE_FLOW = 4


    class usbdevfs_ctrltransfer(ctypes.Structure):
        _fields_ = [
            ("bRequestType", ctypes.c_uint8),
            ("bRequest", ctypes.c_uint8),
            ("wValue", ctypes.c_uint16),
            ("wIndex", ctypes.c_uint16),
            ("wLength", ctypes.c_uint16),
            ("timeout", ctypes.c_uint32),
            ("data", ctypes.c_void_p),
        ]


    def find_device():
        """Discover the ps2avrGB device. Returns dict with dev_path,
        iface_id, unbind_path, bind_path, or None if not found."""
        for root, dirs, files in os.walk("/sys/devices"):
            if "idVendor" not in files:
                continue
            with open(os.path.join(root, "idVendor")) as f:
                if f.read().strip() != "20a0":
                    continue
            if "idProduct" not in files:
                continue
            with open(os.path.join(root, "idProduct")) as f:
                if f.read().strip() != "422d":
                    continue

            # Walk up to find the USB device node (holds busnum/devnum/devpath)
            usb_dev = root
            while usb_dev != "/sys/devices" and usb_dev != "/":
                if os.path.exists(os.path.join(usb_dev, "busnum")):
                    break
                usb_dev = os.path.dirname(usb_dev)
            else:
                continue

            with open(os.path.join(usb_dev, "busnum")) as f:
                busnum = f.read().strip()
            with open(os.path.join(usb_dev, "devnum")) as f:
                devnum = f.read().strip()
            with open(os.path.join(usb_dev, "devpath")) as f:
                devpath = f.read().strip()

            bus_padded = f"{int(busnum):03d}"
            dev_padded = f"{int(devnum):03d}"
            dev_path = f"/dev/bus/usb/{bus_padded}/{dev_padded}"

            # Collect all interfaces with a driver bound
            dev_basename = os.path.basename(usb_dev)
            interfaces = []
            for child in sorted(os.listdir(usb_dev)):
                child_path = os.path.join(usb_dev, child)
                if not os.path.isdir(child_path):
                    continue
                matches_basename = child.startswith(dev_basename + ":")
                if not (matches_basename or child.startswith(devpath + ":")):
                    continue
                driver_link = os.path.join(child_path, "driver")
                if not os.path.islink(driver_link):
                    continue
                driver = os.path.basename(os.readlink(driver_link))
                if matches_basename:
                    suffix = child[len(dev_basename):]
                else:
                    suffix = child[len(devpath):]
                # Extract iface number from ":<config>.<iface>"
                parts = suffix.lstrip(":").split(".")
                if len(parts) >= 2:
                    iface_num = int(parts[1])
                else:
                    iface_num = int(parts[0])
                interfaces.append((suffix, driver, iface_num, child))

            if not interfaces:
                continue

            # Use the last (highest-numbered) interface — the config interface
            suffix, driver, iface_num, child = interfaces[-1]

            iface_id = child
            driver_base = "/sys/bus/usb/drivers"

            return {
                "dev_path": dev_path,
                "iface_id": iface_id,
                "iface_num": iface_num,
                "unbind_path": f"{driver_base}/{driver}/unbind",
                "bind_path": f"{driver_base}/{driver}/bind",
            }

        return None


    def send_report(dev_path, iface_num, data_bytes):
        """Send a SET_REPORT control transfer to the device."""
        ctrl = usbdevfs_ctrltransfer()
        ctrl.bRequestType = 0x21  # OUT, CLASS, INTERFACE
        ctrl.bRequest = 0x09       # SET_REPORT
        ctrl.wValue = 0x0301       # Feature report, Report ID 1
        ctrl.wIndex = iface_num    # Config interface number
        ctrl.wLength = len(data_bytes)
        ctrl.timeout = 1000

        data_buf = ctypes.create_string_buffer(data_bytes)
        ctrl.data = ctypes.cast(data_buf, ctypes.c_void_p)

        fd = os.open(dev_path, os.O_RDWR)
        try:
            fcntl.ioctl(fd, USBDEVFS_CONTROL, ctrl)
        finally:
            os.close(fd)


    def parse_color(hexstr):
        """Parse RRGGBB hex into (r, g, b) in ps2avrGB G,R,B order."""
        if len(hexstr) != 6:
            raise ValueError("Color must be 6 hex digits (RRGGBB)")
        r = int(hexstr[0:2], 16)
        g = int(hexstr[2:4], 16)
        b = int(hexstr[4:6], 16)
        return (g, r, b)


    def cmd_off(dev_path, iface_num):
        """Turn LEDs off."""
        send_report(dev_path, iface_num, bytes([0x01, OPT_MODE, MODE_OFF]))
        print("LEDs off")


    def cmd_on(dev_path, iface_num):
        """Turn LEDs on with color1 mode."""
        send_report(dev_path, iface_num, bytes([0x01, OPT_MODE, MODE_COLOR1]))
        print("LEDs on (color1)")


    def cmd_color(dev_path, iface_num, hexstr):
        """Set color1 and switch to color1 mode."""
        g, r, b = parse_color(hexstr)
        send_report(dev_path, iface_num, bytes([0x01, OPT_COLOR1, g, r, b]))
        send_report(dev_path, iface_num, bytes([0x01, OPT_MODE, MODE_COLOR1]))
        print("Color set to #{}, LEDs on".format(hexstr))


    def cmd_brightness(dev_path, iface_num, val):
        """Set LED brightness (0-255)."""
        b = max(0, min(255, int(val)))
        send_report(dev_path, iface_num, bytes([0x01, OPT_BRIGHTNESS, b]))
        print("Brightness set to {}".format(b))


    def cmd_rainbow(dev_path, iface_num, fade_type=None):
        """Enable rainbow mode with optional fade type."""
        if fade_type is not None:
            ft = {
                "fade": FADE_FADING,
                "immediate": FADE_IMMEDIATE,
                "sequential": FADE_SEQUENTIAL,
                "static": FADE_STATIC,
                "flow": FADE_FLOW,
            }.get(fade_type)
            if ft is None:
                print(
                    "Unknown fade type: {}".format(fade_type),
                    file=sys.stderr,
                )
                print(
                    "Options: fade, immediate, sequential, static,"
                    " flow",
                    file=sys.stderr,
                )
                return
            send_report(dev_path, iface_num, bytes([0x01, OPT_FADE_TYPE, ft]))
        send_report(dev_path, iface_num, bytes([0x01, OPT_MODE, MODE_RAINBOW]))
        label = " ({})".format(fade_type) if fade_type else ""
        print("Rainbow mode{}".format(label))


    def cmd_mode(dev_path, iface_num, mode):
        """Set LED mode directly."""
        m = max(0, min(4, int(mode)))
        names = ["off", "rainbow", "color1", "color2", "color3"]
        send_report(dev_path, iface_num, bytes([0x01, OPT_MODE, m]))
        print("Mode set to {} ({})".format(m, names[m]))


    def usage():
        print(
            "Usage: ps2avr-rgb off | on | color RRGGBB | brightness N |"
            " rainbow [fade|static|flow|immediate|sequential] | mode N",
            file=sys.stderr,
        )


    def main():
        args = sys.argv[1:]
        if not args:
            usage()
            return 1

        dev = find_device()
        if dev is None:
            print("ps2avrGB not found", file=sys.stderr)
            return 1

        dev_path = dev["dev_path"]
        iface_id = dev["iface_id"]
        iface_num = dev["iface_num"]
        unbind_path = dev["unbind_path"]
        bind_path = dev["bind_path"]

        # Unbind config interface from kernel driver
        try:
            fd = os.open(unbind_path, os.O_WRONLY)
            os.write(fd, iface_id.encode())
            os.close(fd)
        except OSError as e:
            print(
                "Failed to unbind {}: {}".format(iface_id, e),
                file=sys.stderr,
            )
            return 1

        ok = True
        try:
            cmd = args[0]
            if cmd == "off":
                cmd_off(dev_path, iface_num)
            elif cmd == "on":
                cmd_on(dev_path, iface_num)
            elif cmd == "color" and len(args) >= 2:
                cmd_color(dev_path, iface_num, args[1])
            elif cmd == "brightness" and len(args) >= 2:
                cmd_brightness(dev_path, iface_num, args[1])
            elif cmd == "rainbow":
                ft = args[1] if len(args) >= 2 else None
                cmd_rainbow(dev_path, iface_num, ft)
            elif cmd == "mode" and len(args) >= 2:
                cmd_mode(dev_path, iface_num, args[1])
            else:
                usage()
                ok = False
        except (ValueError, OSError) as e:
            print("Error: {}".format(e), file=sys.stderr)
            ok = False
        finally:
            # Rebind config interface - always runs, even on KeyboardInterrupt
            try:
                fd = os.open(bind_path, os.O_WRONLY)
                os.write(fd, iface_id.encode())
                os.close(fd)
            except OSError as e:
                print(
                    "Failed to rebind {}: {}".format(iface_id, e),
                    file=sys.stderr,
                )
                ok = False

        return 0 if ok else 1


    if __name__ == "__main__":
        sys.exit(main())
    '';
  no-rgb = pkgs.writeScriptBin "no-rgb" ''
    #!/bin/sh
    set -e

    # Turn off ps2avrGB macropad RGB (unsupported by openrgb)
    ${ps2avr_rgb}/bin/ps2avr-rgb off || true

    # Turn off all other RGB devices via openrgb
    if ${pkgs.openrgb}/bin/openrgb --noautoconnect --list-devices > /dev/null 2>&1; then
      NUM_DEVICES=$(${pkgs.openrgb}/bin/openrgb --noautoconnect --list-devices | grep -E '^[0-9]+: ' | wc -l)
      for i in $(seq 0 $(($NUM_DEVICES - 1))); do
        ${pkgs.openrgb}/bin/openrgb --noautoconnect --device $i --mode static --color 000000 || true
      done
    fi
  '';
in {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usbhid"
  ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [
    "kvm-intel"
    "i2c-dev"
  ];
  hardware.i2c.enable = true;
  services.hardware.openrgb.enable = true;
  boot.kernelParams = [
    "video=DP-1:2560x1440@120"
    "video=HDMI-A-2:2560x1440@120"
  ];
  boot.extraModulePackages = [];
  boot.extraModprobeConfig = '''';
  #blacklist nouveau
  #options nouveauu modeset=0

  fileSystems."/" = {
    device = "/dev/disk/by-label/NIX";
    fsType = "ext4";
    neededForBoot = true;
  };
  systemd.services.no-rgb = {
    description = "Turn off all RGB lighting at boot";
    after = ["multi-user.target"];
    wants = ["multi-user.target"];
    serviceConfig = {
      ExecStartPre = "${pkgs.coreutils}/bin/sleep 5";
      ExecStart = "${no-rgb}/bin/no-rgb";
      Type = "oneshot";
      RemainAfterExit = false;
    };
    wantedBy = ["multi-user.target"];
  };

  #fileSystems."/mnt/arch" = {
  #device = "/dev/disk/by-label/ARCH";
  #fsType = "ext4";
  #};

  #fileSystems."/mnt/other" = {
  #device = "/dev/disk/by-label/OTHER";
  #fsType = "ext4";
  #neededForBoot = true;
  #};

  #fileSystems."/mnt/x9" = {
  #device = "/dev/disk/by-label/x9";
  #fsType = "ext4";
  #neededForBoot = true;
  #};

  #fileSystems."/mnt/other" = {
  #device = "/mnt/x9/other";
  #fsType = "none";
  #options = [ "bind" ];
  #neededForBoot = true;
  #};

  fileSystems."/home/john" = {
    device = "/dev/pool1a/john_home";
    fsType = "ext4";
    neededForBoot = true;
  };

  fileSystems."/mnt/monero" = {
    device = "/dev/pool1b/monero";
    fsType = "ext4";
  };

  fileSystems."/mnt/d" = {
    device = "/dev/disk/by-label/xd";
    fsType = "ntfs";
    neededForBoot = false;
  };

  fileSystems."/mnt/games_a" = {
    device = "/dev/pool1a/games_a";
    fsType = "ext4";
  };

  # Longhorn replica disk for the k3s cluster. The LV (pool1/longhorn, 1.2T)
  # was created manually inside the existing pool1 LUKS volume. Bring up the
  # filesystem on first deploy with:
  #   sudo mkfs.ext4 -L longhorn /dev/mapper/pool1-longhorn
  #   sudo install -d -m 0755 -o root -g root /mnt/longhorn
  # `nofail` keeps the box bootable if the LV is ever absent.
  fileSystems."/mnt/longhorn" = {
    device = "/dev/disk/by-label/longhorn";
    fsType = "ext4";
    options = ["defaults" "noatime" "nofail"];
  };

  #fileSystems."/mnt/games_b" = {
  #device = "/dev/pool1a/games_b";
  #fsType = "ext4";
  #};

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/BOOT";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  # fileSystems."/mnt/efi1" = {
  #   device = "/dev/disk/by-uuid/C84B-9CD5";
  #   fsType = "vfat";
  #   options = [
  #     "fmask=0022"
  #     "dmask=0022"
  #   ];
  # };

  # fileSystems."/mnt/efi2" = {
  #   device = "/dev/disk/by-uuid/B06A-EB76";
  #   fsType = "vfat";
  #   options = [
  #     "fmask=0022"
  #     "dmask=0022"
  #   ];
  # };

  swapDevices = [
    {device = "/dev/disk/by-label/swap";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.cni0.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.flannel.1.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth6a78d611.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth8d9e6a9e.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethe2047d77.useDHCP = lib.mkDefault true;
  # networking.interfaces.wg0-mullvad.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  services.xserver.videoDrivers = ["nvidia"];
  hardware.nvidia = {
    package = config.boot.kernelPackages.nvidiaPackages.legacy_580;
    open = false;
    modesetting.enable = true;
    nvidiaSettings = true;
  };

  hardware.bluetooth.enable = true; # enables support for Bluetooth
  hardware.bluetooth.powerOnBoot = true; # powers up the default Bluetooth controller on boot
  environment.systemPackages = [
    ps2avr_rgb
  ];
}
