{
  config,
  lib,
  pkgs,
  sshKeys,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix") # Proxmox VM virtio drivers
    ./hardware-configuration.nix                # generated by nixos-generate-config on first boot
    ./modules/user-john.nix
  ];

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  boot.initrd.availableKernelModules = [
    "virtio_pci"
    "virtio_scsi"
    "virtio_blk"
    "virtio_net"
    "sd_mod"
    "ext4"
  ];

  networking.hostName = "github";
  networking.networkmanager.enable = true;

  time.timeZone = "America/New_York";
  i18n.defaultLocale = "en_US.UTF-8";
  console = {
    font = "Lat2-Terminus16";
    keyMap = "us";
  };

  environment.systemPackages = with pkgs; [
    git
    fish
    curl
    htop
    k3s   # provides kubectl via `k3s kubectl`
  ];

  programs.gnupg.agent = {
    enable = true;
    enableSSHSupport = true;
  };

  programs.fish.enable = true;

  # ================
  # === Services ===
  # ================

  services.openssh.enable = true;
  users.users."john".openssh.authorizedKeys.keys = sshKeys;

  services.avahi = {
    enable = true;
    nssmdns4 = true;
    publish = {
      enable = true;
      addresses = true;
      domain = true;
      hinfo = true;
      userServices = true;
      workstation = true;
    };
  };

  # Tailscale for tailnet connectivity — no subnet route advertisement.
  services.tailscale.enable = true;

  # ============================================================
  # === k3s — standalone single-node CI cluster              ===
  # ============================================================

  age.secrets.k3s-ci-token = {
    file = ../../secrets/k3s-ci-token.age;
    mode = "0400";
    owner = "root";
    group = "root";
  };

  services.k3s = {
    enable = true;
    role = "server";
    tokenFile = config.age.secrets.k3s-ci-token.path;
    extraFlags = toString [
      "--cluster-init"              # standalone single-node cluster
      "--disable=traefik"           # not used — Gateway API on home cluster
      "--disable=servicelb"         # no external load balancer needed
      "--flannel-backend=host-gw"   # direct routing, lower overhead
    ];
    gracefulNodeShutdown = {
      enable = true;
      shutdownGracePeriod = "20s";
      shutdownGracePeriodCriticalPods = "10s";
    };
  };

  # k3s needs avahi for mDNS — systemd ordering and clean resolv.conf.
  systemd.services.k3s = {
    after = [ "avahi-daemon.service" ];
    wants = [ "avahi-daemon.service" ];
    environment.K3S_RESOLV_CONF = "/etc/rancher/k3s/resolv.conf";
    serviceConfig = {
      TimeoutStopSec = lib.mkForce "30s";
    };
  };

  # Clean resolv.conf for k3s pods — strips the Tailscale MagicDNS search
  # domain (ts.2143.me) to prevent ndots:5 expansion from prepending it
  # to external hostnames. Keeps 100.100.100.100 as the upstream so pods
  # can still resolve tailnet names via MagicDNS.
  environment.etc."rancher/k3s/resolv.conf".text = ''
    nameserver 100.100.100.100
  '';

  # Prevent systemd-networkd from flushing custom ip rules created by
  # external tools (like our pod-CIDR routing fix below). Without this,
  # systemd-networkd removes rules it doesn't know about on restart.
  systemd.network.config.networkConf."ManageForeignRoutingPolicyRules" = "no";

  # Add an ip rule that directs pod CIDR traffic to the main routing table
  # BEFORE Tailscale's rule 5270 sends everything to table 52.
  #
  # Without this, Tailscale's `default dev tailscale0` in table 52 captures
  # pod-to-pod traffic between k3s nodes (because Tailscale's `throw` entries
  # only cover the local node's /24 on cni0, not remote pod CIDRs reached
  # via flannel.1). The result: cross-node pod networking silently fails.
  #
  # Priority 2500 is safely below Tailscale's range (5200-5500), so this rule
  # fires before Tailscale's table 52 lookup at rule 5270.
  # The `to 10.42.0.0/16` narrows it to k3s pod traffic only — non-pod traffic
  # falls through to Tailscale's rules as normal.
  systemd.services.pod-cidr-route = {
    description = "Add ip rule for pod CIDR traffic before Tailscale";
    after = [ "tailscaled.service" "network.target" ];
    wants = [ "tailscaled.service" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      ${pkgs.iproute2}/bin/ip rule add priority 2500 from all to 10.42.0.0/16 lookup main 2>/dev/null || true
    '';
  };

  # Firewall — k3s ports
  networking.firewall.allowedTCPPorts = [
    6443   # k3s API server
    10250  # kubelet
    2379   # etcd client
    2380   # etcd peer
  ];
  networking.firewall.allowedUDPPorts = [
    8472   # k3s flannel
  ];
  networking.firewall.allowedTCPPortRanges = [
    { from = 30000; to = 32767; }  # NodePort range
  ];

  system.stateVersion = "25.11";
}
