# NAS configuration — headless NixOS file server.
#
# Services: ZFS (auto-scrub, sanoid snapshots), Samba (cross-platform),
#           Immich (native NixOS), Avahi/mDNS, Tailscale, SSH.
#
# === ZFS POOL SETUP (one-time, after first boot) ===
#
# 1. Identify drives by serial:
#      ls -l /dev/disk/by-id/ | grep -v part
#
# 2. Create tank pool (RAIDZ1 on 4x 8TB HDDs):
#      sudo zpool create -o ashift=12 \
#        -O atime=off -O compression=lz4 -O xattr=sa -O acltype=posixacl \
#        -O mountpoint=none \
#        tank raidz1 \
#          /dev/disk/by-id/ata-ST8000..._1 \
#          /dev/disk/by-id/ata-ST8000..._2 \
#          /dev/disk/by-id/ata-ST8000..._3 \
#          /dev/disk/by-id/ata-ST8000..._4
#
# 3. Add mirrored special vdev (100GB SSD partitions):
#      sudo zpool add tank special mirror \
#        /dev/disk/by-id/wwn-0x5e83a97923abf0ec-part1 \
#        /dev/disk/by-id/wwn-0x5001b448be24504b-part4
#      sudo zfs set special_small_blocks=32K tank
#
# 4. Add L2ARC read cache (200GB SSD partition on boot SSD):
#      sudo zpool add tank cache /dev/disk/by-id/wwn-0x5001b448be24504b-part5
#
# 5. Create datasets:
#      sudo zfs create -o mountpoint=/tank/share    tank/share
#      sudo zfs create -o mountpoint=/tank/media    tank/media
#      sudo zfs create -o mountpoint=/tank/backups  tank/backups
#      sudo zfs create -o mountpoint=/tank/immich   tank/immich
#      sudo zfs create -o mountpoint=/tank/scratch  tank/scratch
#      sudo zfs create -o mountpoint=/tank/private  tank/private
#      sudo zfs create -o mountpoint=/tank/atticd   tank/atticd

#    Attic Nix cache — chunk-level dedup binary cache shared across all
#    machines. Store paths land on the raidz1 HDDs with lz4 compression:
#      sudo zfs create -o mountpoint=/tank/atticd \
#        -o recordsize=1M -o compression=lz4 -o atime=off tank/atticd
#      sudo chown atticd:atticd /tank/atticd
#
#    Minecraft — pinned entirely to the SSD special mirror for fast chunk
#    reads and mirrored integrity. recordsize=special_small_blocks=128K
#    means every block lands on the SSD, not the raidz1 HDDs.
#      sudo zfs create \
#        -o mountpoint=/tank/minecraft \
#        -o recordsize=128K \
#        -o special_small_blocks=128K \
#        -o compression=lz4 \
#        -o atime=off \
#        tank/minecraft
#      sudo chown john:john /tank/minecraft
#    Immich thumbnails — dedicated child dataset pinned to the SSD special
#    vdev for fast scrolling. recordsize=special_small_blocks=1M means every
#    block written under thumbs/ lands on the SSD mirror, not the raidz1
#    HDDs. Originals under tank/immich stay on HDD.
#      sudo systemctl stop immich-server immich-machine-learning
#      sudo mv /tank/immich/thumbs /tank/immich/thumbs.old   # if it exists
#      sudo zfs create \
#        -o mountpoint=/tank/immich/thumbs \
#        -o recordsize=1M \
#        -o special_small_blocks=1M \
#        -o compression=lz4 \
#        -o atime=off \
#        tank/immich/thumbs
#      sudo chown immich:immich /tank/immich/thumbs
#      sudo chmod 750 /tank/immich/thumbs
#      sudo rsync -aHAX /tank/immich/thumbs.old/ /tank/immich/thumbs/   # if moved
#      sudo systemctl start immich-server immich-machine-learning
#
# 7. Set ownership:
#      sudo chown john:john /tank/share /tank/media /tank/scratch /tank/private
#      sudo chown immich:immich /tank/immich
#      # /tank/backups must be root-owned for OpenSSH ChrootDirectory.
#      # Per-host subdirs are owned by the backup user:
#      sudo chown root:root /tank/backups && sudo chmod 755 /tank/backups
#      for h in arch office closet secu; do
#        sudo zfs create tank/backups/$h   # or just: sudo mkdir /tank/backups/$h
#        sudo chown backup:backup /tank/backups/$h
#      done
#
# 8. Set Samba password:
#      sudo smbpasswd -a john
#
#
# 9. Longhorn backing store — ext4 on sda6, managed by disko.
#    Mounted at /var/lib/longhorn. The ext4 fs label "longhorn"
#    was set via mkfs.ext4 at migration time. No ZFS snapshots needed
#    — Longhorn manages its own backup/replication lifecycle.
#
# 10. Rebuild:
#      sudo nixos-rebuild switch --flake /home/john/dotfiles#nas
#
#
{
  config,
  lib,
  pkgs,
  pkgs-stable,
  inputs,
  compName,
  sshKeys,
  ...
}: {
  # fileSystems and swapDevices are generated by disko (see modules/disko_nas.nix).
  # Boot SSD disaster recovery steps are documented in the disko_nas.nix header.
  imports = [
    ./nas-hardware-configuration.nix
    ./modules/user-john.nix
    ./modules/disko_nas.nix

  ];
  fileSystems."/".neededForBoot = lib.mkForce true;
  home-manager.users."john" = import ./home-cli.nix;
  services.getty.autologinUser = "john";


  boot.loader = {
    systemd-boot.enable = true;
    efi.canTouchEfiVariables = true;
  };

  virtualisation.podman = {
    enable = true;
    dockerCompat = true;
  };

  # ==================
  # === Minecraft  ===
  # ==================

  # instead:
  # nix flake at /tank/minecraft/AoC/flake.nix: nix flake run
  #virtualisation.oci-containers = {
  #backend = "podman";
  #containers.minecraft = {
  #image = "docker.io/itzg/minecraft-server:latest";
  #ports = [ "25565:25565" ];
  #environment = {
  #EULA = "TRUE";
  #TYPE = "NEOFORGE";
  #MEMORY = "6G";
  #};
  #volumes = [
  #"/tank/minecraft:/data"
  #];
  #};
  #};

  # ================
  # === Network  ===
  # ================

  networking.hostName = compName;
  networking.networkmanager.enable = true;
  # ZFS requires a stable hostId — generate with: head -c 8 /etc/machine-id
  networking.hostId = "115e93a1";

  time.timeZone = "America/New_York";
  i18n.defaultLocale = "en_US.UTF-8";
  console = {
    font = "Lat2-Terminus16";
    keyMap = "us";
  };

  environment.systemPackages = with pkgs; [
    git
    fish
    curl
    smartmontools # smartctl — inspect SMART on SATA/SCSI disks
    restic
  ];

  programs.gnupg.agent = {
    enable = true;
    enableSSHSupport = true;
  };

  programs.fish.enable = true;

  # ================
  # === ZFS      ===
  # ================

  boot.zfs.forceImportRoot = false;

  services.zfs.autoScrub = {
    enable = true;
    interval = "monthly";
  };
  services.zfs.trim.enable = true;

  services.sanoid = {
    enable = true;
    datasets = {
      "tank/share" = {
        autosnap = true;
        hourly = 24;
        daily = 30;
        monthly = 6;
      };
      "tank/media" = {
        autosnap = true;
        daily = 7;
        monthly = 3;
      };
      "tank/immich" = {
        autosnap = true;
        hourly = 24;
        daily = 30;
        monthly = 6;
      };
      # tank/immich/thumbs lives on the SSD special vdev and is regenerable
      # from originals — don't waste SSD space snapshotting it.
      "tank/immich/thumbs" = {
        autosnap = false;
      };
      "tank/backups" = {
        autosnap = true;
        daily = 7;
        monthly = 3;
      };
      "tank/private" = {
        autosnap = true;
        daily = 30;
        monthly = 12;
        yearly = 1;
      };
      "tank/minecraft" = {
        autosnap = true;
        hourly = 0;
        daily = 0;
        monthly = 0;
      };
      # k8s Longhorn backup target. Long retention because this is the
      # disaster-recovery layer for cluster PVCs.
      "tank/longhorn-backups" = {
        autosnap = true;
        daily = 30;
        monthly = 12;
      };
    };
  };

  # k3s server — join existing cluster via mDNS (bootstrap without tailscale dependency).
  # NAS runs k3s on ZFS — keep ZFS mounted until k3s drains Longhorn volumes.
  custom.k3sStorageAfter = ["zfs-mount.service"];

  # Dual-stack cluster CIDRs mirror closet's init node config.
  # NAS uses the 10GbE interface at 192.168.5.175 (the 1GbE at .176 is being retired).
  services.k3s.extraFlags = lib.concatStringsSep " " [
    "--server=https://192.168.5.10:6443"
    "--tls-san=nas.local"
    "--tls-san=closet.local"
    "--tls-san=192.168.5.175"
    "--tls-san=192.168.5.10"
    "--cluster-cidr=10.42.0.0/16,fd42:42:42::/56"
    "--service-cidr=10.43.0.0/16,fd42:42:43::/112"
    "--flannel-ipv6-masq"
    "--node-ip=192.168.5.175,fd00:1::175"
    "--node-label=node.longhorn.io/create-default-disk=true"
  ];



  # ================
  # === NFS      ===
  # ================
  #
  # NFSv4 export used SOLELY as a Longhorn backup target for the k3s cluster.
  # No live PVCs sit on this — Longhorn replicates volume data on cluster
  # NVMe (closet + arch) and pushes incremental backups here on a schedule.
  # If this NFS server is unreachable, only new backup uploads pause; live
  # cluster workloads are unaffected.
  #
  # One-time on the NAS before the first rebuild that flips this on:
  #   sudo zfs create -o mountpoint=/tank/longhorn-backups -o recordsize=1M \
  #     -o compression=lz4 -o atime=off tank/longhorn-backups
  #   sudo chown nobody:nogroup /tank/longhorn-backups
  #   sudo chmod 0777 /tank/longhorn-backups
  #
  # The export is scoped to the Tailscale CGNAT range, matching the Samba
  # `hosts allow` line below. Single port (2049) — NFSv4 doesn't need
  # rpcbind/mountd/lockd.
  services.nfs.server = {
    enable = true;
    exports = ''
      /tank/longhorn-backups 100.64.0.0/10(rw,sync,no_subtree_check,no_root_squash,fsid=0) 192.168.5.0/24(rw,sync,no_subtree_check,no_root_squash,fsid=0)
      /tank/frigate           100.64.0.0/10(rw,sync,no_subtree_check,no_root_squash,all_squash,anonuid=1000,anongid=1000,fsid=1) 192.168.5.0/24(rw,sync,no_subtree_check,no_root_squash,all_squash,anonuid=1000,anongid=1000,fsid=1)
    '';
  };

  # ================
  # === Samba    ===
  # ================

  services.samba = {
    enable = true;
    openFirewall = true;
    settings = {
      global = {
        "server string" = "nas";
        "netbios name" = "nas";
        "workgroup" = "WORKGROUP";
        "server role" = "standalone server";
        # Include Tailscale CGNAT so phones / laptops on the tailnet can reach SMB.
        "hosts allow" = "192.168. 10.10. 100.64.0.0/10 127.0.0.1 localhost";
        "hosts deny" = "0.0.0.0/0";
        # macOS compatibility (Finder metadata, resource forks)
        "vfs objects" = "catia fruit streams_xattr";
        "fruit:metadata" = "stream";
        "fruit:model" = "MacSamba";
        "fruit:posix_rename" = "yes";
        "fruit:veto_appledouble" = "no";
        "fruit:nfs_aces" = "no";
        "fruit:wipe_intentionally_left_blank_rfork" = "yes";
        "fruit:delete_empty_adfiles" = "yes";
        "server min protocol" = "SMB2";
        "ea support" = "yes";
        "server signing" = "auto";
        "server smb encrypt" = "auto";
        "map to guest" = "Bad User";
        "host msdfs" = "no";
      };
      share = {
        path = "/tank/share";
        browseable = "yes";
        "read only" = "yes";
        "guest ok" = "yes";
        "write list" = "john ewan brown amandastry";
        "create mask" = "0664";
        "directory mask" = "2775";
      };
      media = {
        path = "/tank/media";
        browseable = "yes";
        "read only" = "yes";
        "valid users" = "john ewan brown amandastry";
      };
      scratch = {
        path = "/tank/scratch";
        browseable = "yes";
        "read only" = "no";
        "valid users" = "john ewan brown amandastry";
        "create mask" = "0664";
        "directory mask" = "2775";
      };
      private = {
        path = "/tank/private/%U";
        browseable = "yes";
        "read only" = "no";
        "valid users" = "john amandastry";
        "create mask" = "0600";
        "directory mask" = "0700";
      };
    };
  };

  services.samba-wsdd = {
    enable = true;
    openFirewall = true;
  };

  # ================
  # === Immich   ===
  # ================

  services.immich = {
    enable = true;
    host = "0.0.0.0";
    port = 2283;
    openFirewall = true;
    mediaLocation = "/tank/immich";
    machine-learning.enable = true;
    database.enable = true;
    redis.enable = true;

    # Public serving of /share/* is handled by the k8s `immich-public-proxy`
    # workload fronting images.2143.me. This setting only controls the URL
    # Immich embeds in generated share links (and a few other UI-copied URLs).
    settings.server.externalDomain = "https://images.2143.me";
  };

  # ================
  # === Services ===
  # ================

  services.openssh.enable = true;
  users.users."john".openssh.authorizedKeys.keys = sshKeys;

  users.groups.backup = {};
  users.users.backup = {
    isNormalUser = true;
    group = "backup";
    home = "/tank/backups";
    createHome = false;
    shell = pkgs.shadow + "/bin/nologin";
    openssh.authorizedKeys.keys = [
      # Dedicated backup keypair — NOT john's personal keys.
      # Generate: ssh-keygen -t ed25519 -f /tmp/backup-key -N "" -C "backup@nas"
      # Paste the public key here, encrypt the private key with agenix.
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHc7Lm/K9+ayv0s8Emk8z89Cgtzm5jexAUfdcjoJAinw backup@nas"
    ];
  };

  services.openssh.extraConfig = ''
    Match User backup
      ForceCommand internal-sftp
      ChrootDirectory /tank/backups
      AllowTcpForwarding no
      X11Forwarding no
      PermitTunnel no
  '';

  services.avahi = {
    enable = true;
    nssmdns4 = true;
    publish = {
      enable = true;
      addresses = true;
      domain = true;
      hinfo = true;
      userServices = true;
      workstation = true;
    };
  };

  # ── APC UPS monitoring ────────────────────────────────────────────
  # Dedicated UPS via USB. Fires HA webhooks on power events.
  age.secrets.hass-webhooks = {
    file = ../secrets/hass-webhooks.age;
    owner = "root";
  };
  services.apcupsd = {
    enable = true;
    configText = ''
      UPSCABLE usb
      UPSTYPE usb
      DEVICE
      ONBATTERYDELAY 6
      BATTERYLEVEL 90
      MINUTES 5
    '';
    hooks = {
      onbattery = ''
        set -a; source /run/agenix/hass-webhooks; set +a
        ${pkgs.curl}/bin/curl -s -X POST "$NAS_ONBATTERY_URL"
        ${pkgs.util-linux}/bin/wall 'UPS on battery — NAS shutting down when critical'
      '';
      offbattery = ''
        set -a; source /run/agenix/hass-webhooks; set +a
        ${pkgs.curl}/bin/curl -s -X POST "$NAS_OFFBATTERY_URL"
        ${pkgs.util-linux}/bin/wall 'UPS power restored on NAS'
      '';
      doshutdown = ''
        ${pkgs.util-linux}/bin/wall 'UPS battery critical — shutting down NAS NOW'
        sleep 5
        ${pkgs.systemd}/bin/systemctl poweroff -f
      '';
    };
  };
  # ====================
  # === Attic Cache ===
  # ====================

  # ZFS dataset (one-time): sudo zfs create -o mountpoint=/tank/atticd \
  #   -o recordsize=1M -o compression=lz4 -o atime=off tank/atticd
  #   sudo chown atticd:atticd /tank/atticd

  # Declarative cache bootstrap — creates + configures the cache on first boot.
  # Token generation remains imperative: atticd-atticadm make-token
  systemd.services.attic-cache-bootstrap = {
    description = "Ensure Attic cache 2143nix exists and is configured";
    after = [ "atticd.service" ];
    requires = [ "atticd.service" ];
    serviceConfig.Type = "oneshot";
    serviceConfig.RemainAfterExit = true;
    script = ''
      TOKEN=$(</run/agenix/attic-admin-token)
      ${pkgs.attic-client}/bin/attic login nas http://localhost:8280 "$TOKEN"
      if ! ${pkgs.attic-client}/bin/attic cache info 2143nix >/dev/null 2>&1; then
        ${pkgs.attic-client}/bin/attic cache create 2143nix
      fi
      ${pkgs.attic-client}/bin/attic cache configure 2143nix --priority 41
    '';
  };

  services.atticd = {
    enable = true;
    environmentFile = config.age.secrets.attic-jwt-secret.path;
    settings = {
      listen = "[::]:8280";
      allowed-hosts = ["nas.ts.2143.me" "nas.ts.2143.me:8280" "nas" "nas:8280" "nas.local" "nas.local:8280" "localhost" "localhost:8280" "100.64.0.14" "100.64.0.14:8280"];
      api-endpoint = "http://nas:8280/";
      database.url = "sqlite:///tank/atticd/server.db?mode=rwc";
      storage = {
        type = "local";
        path = "/tank/atticd/storage";
      };
    };
  };


  age.secrets.attic-jwt-secret = {
    file = ../secrets/attic-jwt-secret.age;
    mode = "0400";
    owner = "atticd";
    group = "atticd";
  };

  # Persistent user for ZFS dataset ownership.
  # The nixpkgs module already defines atticd as a system user; these
  # declarations merge with the module's defaults.
  users.users.atticd = {
    isSystemUser = true;
    group = "atticd";
  };
  users.groups.atticd = {};

  # Disable DynamicUser + PrivateUsers so atticd can own ZFS datasets
  # that persist across reboots. ReadWritePaths covers the full
  # /tank/atticd tree (database + storage subdirectory).
  systemd.services.atticd.serviceConfig = {
    DynamicUser = lib.mkForce false;
    PrivateUsers = lib.mkForce false;
    ReadWritePaths = [ "/tank/atticd" ];
  };

  security.rtkit.enable = true;

  networking.firewall = {
    enable = true;
    allowedTCPPorts = [


      111 # rpcbind (NFS)
      2049 # nfsv4 (NFS) — Longhorn backup target
      2283 # immich (immich-server)
      25565 # minecraft (paperMC)
      5580 # matter-server (hostNetwork pod)
      8280 # attic nix cache — nas-configuration.nix:557
      10250 # kubelet (k3s agent)

      20048 # rpc.mountd (NFS)
    ];
    allowedTCPPortRanges = [
      { from = 30000; to = 32767; } # Kubernetes NodePort range
    ];
    allowedUDPPorts = [

      111 # rpcbind (NFS)
      20048 # rpc.mountd (NFS)
      8472 # flannel VXLAN
    ];
  };

  # Attic cache via loopback — no external cache dependency.
  nix.settings.substituters = lib.mkForce [
    "http://localhost:8280/2143nix"
  ];

  # Longhorn replica storage — ext4 on sda6 (disk label "longhorn").
  # Mounted at /mnt/longhorn directly (not a symlink) so the instance-manager
  # container can bind-mount it without symlink resolution issues.
  fileSystems."/mnt/longhorn" = {
    device = "/dev/disk/by-label/longhorn";
    fsType = "ext4";
  };

  system.stateVersion = "26.05";
}


