#!/usr/bin/env python3
"""
Frigate GenAI sidecar — multi-frame event descriptions via Temporal + vision LLM.

Listens to MQTT for completed Frigate events, starts a Temporal "GenAI"
workflow that extracts frames, fetches snapshots, calls a vision LLM, and
writes the description back to Frigate.

Configuration read from two JSON files (generated by Nix):
  /var/lib/frigate-genai-sidecar/prompts.json
  /var/lib/frigate-genai-sidecar/provider.json

Environment:
  FRIGATE_BASE_URL  — Frigate HTTP API (default: http://localhost:5000)
  MQTT_HOST         — MQTT broker (default: localhost)
  MQTT_PORT         — MQTT port (default: 1883)
  TEMPORAL_ADDRESS  — Temporal frontend (default: 192.168.5.10:32682)
"""

import argparse
import asyncio
import json
import logging
import math
import os
import subprocess
import sys
import tempfile
import threading
import time
import urllib.request
from datetime import timedelta
from pathlib import Path

from PIL import Image, ImageOps
import paho.mqtt.client as mqtt
from temporalio import activity, workflow
from temporalio.common import RetryPolicy, SearchAttributeKey, SearchAttributePair, TypedSearchAttributes
from temporalio.client import Client
from temporalio.worker import Worker
from temporalio.exceptions import ApplicationError
from temporalio.api.enums.v1 import IndexedValueType
from temporalio.api.operatorservice.v1 import AddSearchAttributesRequest


log = logging.getLogger("frigate-genai-sidecar")

# ── constants ───────────────────────────────────────────────────────

TASK_QUEUE = "genai-tasks"
FFMPEG_TASK_QUEUE = "genai-tasks-ffmpeg"
GEMINI_TASK_QUEUE = "genai-tasks-gemini"
OLLAMA_TASK_QUEUE = "genai-tasks-ollama"
FRAMES_DIR = Path("/var/lib/frigate-genai-sidecar/frames")
AGENT_LOGS_DIR = Path("/var/lib/frigate-genai-sidecar/agent-logs")
# Typed search attributes for Temporal workflows
_SEARCH_CAMERA = SearchAttributeKey.for_keyword("Camera")
_SEARCH_LABEL = SearchAttributeKey.for_keyword("Label")
_SEARCH_EVENT_ID = SearchAttributeKey.for_keyword("EventId")
_SEARCH_DURATION = SearchAttributeKey.for_int("Duration")
_SEARCH_COST = SearchAttributeKey.for_int("Cost")
_SEARCH_MODEL = SearchAttributeKey.for_keyword("Model")

_stats: dict = {
    "events_processed": 0,
    "model_counts": {},
    "last_event": None,
    "mqtt_connected": False,
    "temporal_connected": False,
}

# ── HTML UI (unchanged) ─────────────────────────────────────────────

UI_HTML = r'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Frigate GenAI</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{background:#0f0f1a;color:#d4d4d8;font:13px system-ui,sans-serif;padding:16px}
h1{font-size:18px;font-weight:600;margin-bottom:12px;color:#fff}
.stats{display:flex;gap:20px;margin-bottom:16px;padding:10px 14px;background:#14142a;border-radius:8px;font-size:12px}
.stat{display:flex;flex-direction:column}
.stat-label{color:#666;font-size:10px;text-transform:uppercase;letter-spacing:.5px}
.stat-value{color:#d4d4d8;font-size:14px;font-weight:500}
.stat-value.ok{color:#4ade80}
.stat-value.off{color:#f87171}
table{width:100%;border-collapse:collapse}
th,td{padding:8px 10px;text-align:left;border-bottom:1px solid #1e1e32}
th{font-weight:500;color:#888;font-size:11px;text-transform:uppercase}
tr:hover{background:#1a1a2e}
img{border-radius:4px;max-height:60px}
.btn{background:#2d2d4a;color:#c8c8d0;border:1px solid #3d3d5e;padding:5px 12px;border-radius:5px;cursor:pointer;font-size:12px}
.btn:hover{background:#3d3d5e}
.btn:disabled{opacity:.4;cursor:default}
.ok{color:#4ade80}
.err{color:#f87171}
.desc{max-width:400px;font-size:11px;color:#999;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.loading{text-align:center;padding:40px;color:#666}
.toggle-wrap{display:flex;align-items:center;gap:8px;margin-bottom:16px}
.toggle{position:relative;width:40px;height:22px;background:#2d2d4a;border-radius:11px;cursor:pointer;border:1px solid #3d3d5e;transition:background .2s}
.toggle.on{background:#4ade80;border-color:#4ade80}
.toggle::after{content:'';position:absolute;width:16px;height:16px;border-radius:50%;background:#d4d4d8;top:2px;left:2px;transition:transform .2s}
.toggle.on::after{transform:translateX(18px);background:#0f0f1a}
.toggle-label{font-size:12px;color:#888}
.toggle-label.on{color:#4ade80}
</style>
</head>
<body>
<h1>Frigate GenAI Reprocess</h1>
<div class="toggle-wrap"><span id="toggle-btn" class="toggle" onclick="togglePause()"></span><span id="toggle-label" class="toggle-label">Ollama on</span></div>
<div id="stats" class="loading" style="margin-bottom:12px">Loading stats...</div>
<div id="app" class="loading">Loading events...</div>
<script>
const SIDECAR = "";
const DESCRIBE = ["person","dog","cat","package","face","fox","deer","bear","horse","cow","raccoon","bird","motorcycle","bicycle","school_bus","boat","robot_lawnmower","umbrella","amazon","fedex","ups","usps","dhl","an_post","purolator","postnl","nzpost","postnord","gls","dpd","royal_mail","canada_post"];
async function load() {
  try {
    const r = await fetch("/api/events?limit=100");
    const events = await r.json();
    const filtered = events.filter(e => DESCRIBE.includes(e.label) && e.has_clip && e.end_time);
    if (!filtered.length) { app.innerHTML = '<p>No eligible events found.</p>'; return; }
    let html = '<table><tr><th>Snapshot</th><th>Camera</th><th>Label</th><th>Duration</th><th>Description</th><th></th></tr>';
    for (const e of filtered) {
      const dur = (e.end_time - e.start_time).toFixed(1) + "s";
      const desc = (e.data?.description || "").substring(0, 120);
      html += '<tr>';
      html += '<td><img src="/api/events/' + e.id + '/snapshot.jpg" loading="lazy"></td>';
      html += '<td>' + e.camera + '</td>';
      html += '<td>' + e.label + '</td>';
      html += '<td>' + dur + '</td>';
      html += '<td class="desc" title="' + (e.data?.description || "").replace(/"/g,"&quot;") + '">' + (desc || "—") + '</td>';
      html += '<td><button class="btn" onclick="reprocess(\'' + e.id + '\',this)">Reprocess</button></td>';
      html += '</tr>';
    }
    html += '</table>';
    app.innerHTML = html;
  } catch(err) { app.innerHTML = '<p class="err">Failed to load: ' + err.message + '</p>'; }
}

async function reprocess(id, btn) {
  btn.textContent = "..."; btn.disabled = true;
  try {
    const r = await fetch("/reprocess/" + id, { method: "POST" });
    if (r.ok) { btn.textContent = "Sent!"; btn.classList.add("ok"); }
    else { btn.textContent = "Failed"; btn.classList.add("err"); }
  } catch(e) { btn.textContent = "Error"; btn.classList.add("err"); }
  setTimeout(() => { btn.textContent = "Reprocess"; btn.classList.remove("ok","err"); btn.disabled = false; }, 5000);
}
async function loadStats() {
  try {
    const r = await fetch("/api/stats");
    const s = await r.json();
    const mqtt = s.mqtt_connected ? '<span class="ok">OK</span>' : '<span class="off">Disconnected</span>';
    const models = Object.entries(s.model_counts).map(([m,c]) => m.split("/").pop()+": "+c).join(" | ") || "—";
    const statsEl = document.getElementById("stats");
    statsEl.className = "stats";
    statsEl.innerHTML = '<div class="stat"><span class="stat-label">MQTT</span><span class="stat-value">'+mqtt+'</span></div><div class="stat"><span class="stat-label">Processed</span><span class="stat-value">'+s.events_processed+'</span></div><div class="stat"><span class="stat-label">Last</span><span class="stat-value">'+(s.last_event||"—")+'</span></div><div class="stat"><span class="stat-label">Models</span><span class="stat-value">'+models+'</span></div>';
  } catch(e) { /* stats will stay as loading */ }
}
async function loadPause() {
  try {
    const r = await fetch("/api/pause");
    const d = await r.json();
    if (d.paused) { setPause(true); }
  } catch(e) {}
}

async function togglePause() {
  const r = await fetch("/api/pause", {method:"POST"});
  const d = await r.json();
  setPause(d.paused);
}

function setPause(paused) {
  const btn = document.getElementById("toggle-btn");
  const lbl = document.getElementById("toggle-label");
  btn.className = "toggle" + (paused ? "" : " on");
  lbl.textContent = paused ? "Ollama off" : "Ollama on";
  lbl.className = "toggle-label" + (paused ? "" : " on");
}

loadPause();
loadStats();
load();
</script>
</body>
</html>'''


# ── config ──────────────────────────────────────────────────────────

def load_json(path: str) -> dict:
    with open(path) as f:
        return json.load(f)


# ── frame extraction ────────────────────────────────────────────────

def extract_frames(
    camera: str,
    start_time: float,
    end_time: float,
    fps: float,
    max_frames: int = 30,
    max_width: int = 1280,
    jpg_quality: int = 85,
) -> list[bytes]:
    """
    Extract JPEG frames from Frigate recording via HLS.

    Returns list of JPEG byte strings, chronologically ordered.
    """
    base_url = os.environ.get("FRIGATE_BASE_URL", "http://localhost:5000")
    hls_url = (
        f"{base_url}/vod/{camera}"
        f"/start/{int(start_time)}/end/{int(math.ceil(end_time))}"
        f"/index.m3u8"
    )
    duration = end_time - start_time

    log.info(
        "Extracting up to %d frames at %.1ffps from %s (%.1fs clip)",
        max_frames, fps, hls_url, duration,
    )

    with tempfile.TemporaryDirectory(prefix="frigate-genai-") as tmp:
        cmd = [
            "ffmpeg",
            "-y",
            "-loglevel", "error",
            "-i", hls_url,
            "-vf", f"fps={fps},scale=1280:-2",
            "-frames:v", str(max_frames),
            "-q:v", str(max(1, min(31, int(31 - 31 * jpg_quality / 100)))),
            f"{tmp}/frame_%03d.jpg",
        ]
        try:
            result = subprocess.run(
                cmd, check=True, timeout=60, capture_output=True, text=True,
            )
        except subprocess.CalledProcessError as e:
            stderr = (e.stderr or "").strip()
            # 404 is expected when recording isn't ready — the activity retries
            if "404 Not Found" in stderr or "Connection refused" in stderr:
                log.debug("ffmpeg: recording not ready for %s", hls_url)
            else:
                log.error("ffmpeg failed: %s", stderr)
            return []
        except subprocess.TimeoutExpired:
            log.error("ffmpeg timed out extracting frames")
            return []

        frames = []
        for p in sorted(Path(tmp).glob("frame_*.jpg")):
            frames.append(p.read_bytes())

        if not frames:
            log.warning("No frames extracted")
        else:
            log.info("Extracted %d frames", len(frames))

        return frames


def fetch_snapshot(event_id: str) -> bytes | None:
    """Fetch the event snapshot (close-up of tracked object)."""
    base_url = os.environ.get("FRIGATE_BASE_URL", "http://localhost:5000")
    url = f"{base_url}/api/events/{event_id}/snapshot.jpg"
    try:
        req = urllib.request.Request(url)
        with urllib.request.urlopen(req, timeout=15) as resp:
            return resp.read()
    except Exception as e:
        log.warning("Failed to fetch snapshot for %s: %s", event_id, e)
        return None




# ── LiteLLM provider ────────────────────────────────────────────────

def call_litellm(
    prompt_text: str,
    images: list[bytes],
    snapshot: bytes | None,
    label: str,
    provider_cfg: dict,
    model: str,
) -> tuple[str | None, str | None]:
    """Call LiteLLM (OpenAI-compatible) with images as base64 data URIs."""
    import base64
    from openai import OpenAI

    api_key = os.environ.get(provider_cfg.get("api_key_env", ""), "")
    if not api_key:
        log.error("LiteLLM API key not found in env var %s", provider_cfg.get("api_key_env"))
        return None, None
    base_url = provider_cfg.get("base_url", os.environ.get("OPENAI_BASE_URL", ""))
    client = OpenAI(api_key=api_key, base_url=base_url, timeout=120.0)

    content: list[dict] = [{"type": "text", "text": prompt_text}]

    for img in images:
        b64 = base64.b64encode(img).decode()
        content.append({
            "type": "image_url",
            "image_url": {"url": f"data:image/jpeg;base64,{b64}"},
        })

    if snapshot:
        content.append({
            "type": "text",
            "text": (
                f"The next image is a close-up of the {label}. "
                "Use it for appearance detail (clothing, items, expression); "
                "use the preceding full frames for scene context, movement, "
                "and event progression."
            ),
        })
        b64 = base64.b64encode(snapshot).decode()
        content.append({
            "type": "image_url",
            "image_url": {"url": f"data:image/jpeg;base64,{b64}"},
        })

    log.info("Calling LiteLLM %s with %d images + 1 snapshot", model, len(images))

    try:
        response = client.chat.completions.create(
            model=model,
            messages=[{"role": "user", "content": content}],
        )
        return response.choices[0].message.content, model
    except Exception as e:
        log.error("LiteLLM call failed: %s", e)
        return None, None




# ── Frigate API ─────────────────────────────────────────────────────

def update_event_description(event_id: str, description: str) -> bool:
    """Write description back to Frigate's event."""
    base_url = os.environ.get("FRIGATE_BASE_URL", "http://localhost:5000")
    url = f"{base_url}/api/events/{event_id}/description"
    payload = json.dumps({"description": description}).encode()
    try:
        req = urllib.request.Request(
            url, data=payload, method="POST",
            headers={"Content-Type": "application/json"},
        )
        with urllib.request.urlopen(req, timeout=10) as resp:
            return resp.status == 200
    except Exception as e:
        log.error("Failed to update event %s: %s", event_id, e)
        return False


# ── prompt composition ──────────────────────────────────────────────

def compose_prompt(
    prompts: dict,
    camera: str,
    label: str,
    num_frames: int,
) -> str:
    """Compose the prompt from the Nix-generated template blocks."""
    base = prompts.get("base", "")
    camera_desc = prompts.get("camera", {}).get(camera, "")
    suffix = prompts.get("suffix", "")
    label_hint = prompts.get("label", {}).get(label, "")

    base = base.replace("{label}", label)

    parts = [base]
    if camera_desc:
        parts.append(camera_desc)
    if label_hint:
        parts.append(label_hint)
    if suffix:
        parts.append(suffix)

    prompt = " ".join(parts)
    prompt = prompt.replace("{label}", label)

    first_line = "FIRST: State exactly how many image frames you received."
    if first_line in prompt:
        prompt = prompt.replace(
            first_line,
            f"You are viewing {num_frames} chronological frames from a security camera, "
            f"at ~1-4 frames per second, plus one close-up detail image",
        )
    return prompt


# ── Frame viewer helpers ─────────────────────────────────────────────


def _resize_frame(img_bytes: bytes, max_width: int, quality: int = 60) -> bytes:
    """Resize a JPEG frame to max_width, preserving aspect ratio. Returns JPEG bytes."""
    from io import BytesIO
    img = Image.open(BytesIO(img_bytes))
    if img.mode != "RGB":
        img = img.convert("RGB")
    if img.width > max_width:
        img = ImageOps.exif_transpose(img)
        img.thumbnail((max_width, max_width))
    buf = BytesIO()
    img.save(buf, format="JPEG", quality=quality)
    return buf.getvalue()


def _load_frames(
    frame_files: list[Path],
    start: int,
    end: int,
    max_width: int | None = None,
    quality: int = 60,
) -> list[bytes]:
    """Load and optionally resize frames [start, end] inclusive."""
    result = []
    for i in range(max(0, start), min(end + 1, len(frame_files))):
        data = frame_files[i].read_bytes()
        if max_width:
            data = _resize_frame(data, max_width, quality)
        result.append(data)
    return result


def _build_image_content(data: bytes) -> dict:
    """Build an image_url content part for an OpenAI-compatible messages array."""
    import base64
    b64 = base64.b64encode(data).decode()
    return {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{b64}"}}


def _tool_view_frames_schema() -> dict:
    return {
        "type": "function",
        "function": {
            "name": "view_frames",
            "description": (
                "View frames from the recording by index range and resolution. "
                "Use 'low' resolution to scan/overview, 'high' for close inspection. "
                "Pass the same index for start and end to view a single frame."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "start": {"type": "integer", "description": "Frame index to start at (0-based, inclusive)"},
                    "end": {"type": "integer", "description": "Frame index to end at (inclusive, same as start for single frame)"},
                    "resolution": {
                        "type": "string",
                        "enum": ["low", "high"],
                        "description": "'low' = 640px wide, 'high' = 1280px wide",
                    },
                },
                "required": ["start", "end", "resolution"],
            },
        },
    }


def _tool_frame_count_schema() -> dict:
    return {
        "type": "function",
        "function": {
            "name": "frame_count",
            "description": "Return the total number of extracted frames available for this recording.",
            "parameters": {"type": "object", "properties": {}, "required": []},
        },
    }



# ═════════════════════════════════════════════════════════════════════
# Temporal Activities
# ═════════════════════════════════════════════════════════════════════


async def _run_with_heartbeat(func, *args, interval: float = 5.0):
    """Run a sync function in a thread, heartbeating every `interval` seconds.

    Prevents Temporal from cancelling the activity while the thread is busy
    (e.g. waiting for a slow LLM).
    """
    task = asyncio.create_task(asyncio.to_thread(func, *args))
    while not task.done():
        try:
            await asyncio.wait_for(asyncio.shield(task), timeout=interval)
        except TimeoutError:
            activity.heartbeat()
    return task.result()
@activity.defn(name="select_model")
async def select_model_activity(input_data: dict) -> str:
    """Select the LLM model for this workflow. Activity so it's visible
    in Temporal history and can run on any worker (distributed-safe)."""
    import random
    provider_cfg = load_json(input_data.get("provider_path",
        "/var/lib/frigate-genai-sidecar/provider.json"))
    models = provider_cfg.get("model", ["gemini/gemini-2.5-flash"])
    if not isinstance(models, list):
        models = [models]

    paused = input_data.get("paused-ollama", False)
    if paused:
        gemini_models = [m for m in models if m.startswith("gemini/")]
        model = gemini_models[0] if gemini_models else "gemini/gemini-2.5-flash"
        log.warning("Paused ollama — forcing gemini model: %s", model)
    else:
        model = random.choice(models)

    log.info("Selected model %s (paused=%s)", model, paused)
    return model
@activity.defn(name="extract_frames")
async def extract_frames_activity(input_data: dict) -> tuple[str, int]:
    """Extract frames via ffmpeg, save to disk. Returns (frames_dir, frame_count)."""
    camera = input_data["camera"]
    start_time = input_data["start_time"]
    end_time = input_data["end_time"]
    event_id = input_data["event_id"]

    duration = end_time - start_time
    fps = max(1, min(4, 4 / max(1, duration)))
    max_frames = max(4, min(300, int(duration * fps)))

    frames_dir = FRAMES_DIR / event_id
    frames_dir_str = str(frames_dir)
    log.info(
        "Activity extract_frames: event=%s camera=%s duration=%.1fs max_frames=%d dir=%s",
        event_id, camera, duration, max_frames, frames_dir,
    )

    frames = await _run_with_heartbeat(
        extract_frames, camera, start_time, end_time, fps, max_frames,
    )
    if not frames:
        raise ApplicationError(
            f"Recording not ready for {event_id}", non_retryable=False,
        )

    frames_dir.mkdir(parents=True, exist_ok=True)
    for i, frame_bytes in enumerate(frames):
        (frames_dir / f"frame_{i:03d}.jpg").write_bytes(frame_bytes)

    log.info("Extracted %d ffmpeg frames to %s", len(frames), frames_dir)
    return frames_dir_str, len(frames)

@activity.defn(name="fetch_snapshot")
async def fetch_snapshot_activity(input_data: dict) -> str:
    """Fetch the snapshot from Frigate API, save to disk. Returns frames_dir."""
    event_id = input_data["event_id"]
    frames_dir = FRAMES_DIR / event_id
    frames_dir.mkdir(parents=True, exist_ok=True)
    log.info("frames_dir=%s", frames_dir)
    snapshot_bytes = await _run_with_heartbeat(fetch_snapshot, event_id)
    if snapshot_bytes:
        (frames_dir / "snapshot.jpg").write_bytes(snapshot_bytes)
    return str(frames_dir)


@activity.defn(name="run_genai")
async def run_genai_activity(input_data: dict, frames_dir: str) -> str | None:
    """Load frames and snapshot from disk, compose prompt, call GenAI provider."""
    event_id = input_data["event_id"]
    camera = input_data["camera"]
    label = input_data["label"]
    prompts_path = input_data["prompts_path"]
    provider_path = input_data["provider_path"]
    model = input_data.get("model", "gemini/gemini-2.5-flash")

    frames_path = Path(frames_dir)
    frame_files = sorted(frames_path.glob("frame_*.jpg"))
    log.info("Activity run_genai: event=%s camera=%s label=%s frames=%d",
             event_id, camera, label, len(frame_files))

    try:
        prompts = load_json(prompts_path)
        provider_cfg = load_json(provider_path)
    except (OSError, json.JSONDecodeError) as e:
        log.error("Failed to load config in run_genai: %s", e)
        raise RuntimeError(f"Failed to load config: {e}") from e

    # Read frames + snapshot from disk
    frames = []
    for fp in frame_files:
        frames.append(fp.read_bytes())
    snapshot_path = frames_path / "snapshot.jpg"
    snapshot = snapshot_path.read_bytes() if snapshot_path.exists() else None

    if input_data.get("skip_frames"):
        prompt_text = prompts.get("car", prompts.get("base", "Identify this vehicle.")).replace("{label}", label)
    else:
        prompt_text = compose_prompt(prompts, camera, label, len(frames))

    description, model_used = await _run_with_heartbeat(
        call_litellm, prompt_text, frames, snapshot, label, provider_cfg, model,
    )

    if model_used:
        _stats["model_counts"][model_used] = _stats["model_counts"].get(model_used, 0) + 1
    _stats["events_processed"] += 1
    _stats["last_event"] = f"{camera}/{label}/{event_id[:12]}"

    return description

@activity.defn(name="run_genai_agent")
async def run_genai_agent_activity(input_data: dict, frames_dir: str) -> str | None:
    """Agentic GenAI: model uses tool calls to explore frames selectively.

    Works with any model. Models that don't call tools produce a single-turn
    response (functionally equivalent to the dump-all path).
    """
    import base64
    import json as _json
    from openai import OpenAI

    event_id = input_data["event_id"]
    camera = input_data["camera"]
    label = input_data["label"]
    prompts_path = input_data["prompts_path"]
    provider_path = input_data["provider_path"]
    model = input_data.get("model", "gemini/gemini-2.5-flash")

    frames_path = Path(frames_dir)
    frame_files = sorted(frames_path.glob("frame_*.jpg"))
    max_frames = len(frame_files)
    log.info("Activity run_genai_agent: event=%s camera=%s label=%s frames=%d model=%s",
             event_id, camera, label, max_frames, model)

    # Load config
    try:
        prompts = load_json(prompts_path)
        provider_cfg = load_json(provider_path)
    except (OSError, _json.JSONDecodeError) as e:
        log.error("Failed to load config in run_genai_agent: %s", e)
        raise RuntimeError(f"Failed to load config: {e}") from e

    # Build OpenAI client
    api_key = os.environ.get(provider_cfg.get("api_key_env", ""), "")
    if not api_key:
        log.error("API key not found in env var %s", provider_cfg.get("api_key_env"))
        raise RuntimeError("API key not configured")
    base_url = provider_cfg.get("base_url", os.environ.get("OPENAI_BASE_URL", ""))
    client = OpenAI(api_key=api_key, base_url=base_url, timeout=120.0)

    # Snapshot (always present — fetch_snapshot_activity runs first)
    snapshot_path = frames_path / "snapshot.jpg"
    snapshot = snapshot_path.read_bytes() if snapshot_path.exists() else None

    # System prompt with context caching
    base_prompt = prompts.get("base", "Describe what is happening in these security camera frames.")
    system_prompt = (
        f"{base_prompt}\n\n"
        f"You are an AI analyzing frames from a security camera. Camera: {camera}. "
        f"Detected label: {label}. "
        f"Use the view_frames(start, end, resolution) tool to explore frames. "
        f"Use 'low' resolution (640px) to scan/overview large ranges. "
        f"Use 'high' resolution (1280px) for close inspection of interesting frames. "
        f"Use frame_count() to check how many frames are available. "
        f"Aim to describe the event concisely — 1-3 sentences. "
        f"Be specific: colors, vehicles, clothing, actions, direction of movement."
    )

    # Build initial messages with context caching
    messages = [
        {
            "role": "system",
            "content": system_prompt,
            "cache_control": {"type": "ephemeral"},
        },
    ]

    user_content = []
    if snapshot:
        user_content.append(_build_image_content(snapshot))
    user_content.append({
        "type": "text",
        "text": (
            f"Camera: {camera}. Detected: {label}. "
            f"Recording has {max_frames} frames available (0-{max_frames - 1}). "
            f"The image above is a close-up snapshot. "
            f"Use view_frames to explore the full recording."
        ),
    })
    messages.append({
        "role": "user",
        "content": user_content,
        "cache_control": {"type": "ephemeral"},
    })

    tools = [_tool_view_frames_schema(), _tool_frame_count_schema()]

    # Accumulators
    total_cost = {"prompt": 0, "completion": 0, "cached": 0}
    turns_low = 0
    turns_high = 0
    description = None

    # Agent loop
    for turn in range(15):
        activity.heartbeat()

        response = client.chat.completions.create(
            model=model,
            messages=messages,
            tools=tools,
            tool_choice="auto",
        )
        msg = response.choices[0].message
        u = response.usage
        prompt_tok = u.prompt_tokens
        comp_tok = u.completion_tokens
        cached_tok = getattr(u, "cached_tokens", 0) or 0
        total_cost["prompt"] += prompt_tok
        total_cost["completion"] += comp_tok
        total_cost["cached"] += cached_tok
        log.info("Agentic turn %d/%d: %d prompt, %d completion, %d cached",
                 turn + 1, 15, prompt_tok, comp_tok, cached_tok)

        # Text response — model is done
        if not msg.tool_calls:
            description = msg.content
            log.info("Agentic: model done after %d turns", turn + 1)
            break

        # Process tool calls
        messages.append(msg.model_dump(exclude_none=True))

        for tc in msg.tool_calls:
            func_name = tc.function.name
            try:
                args = _json.loads(tc.function.arguments)
            except _json.JSONDecodeError:
                tool_result = "Error: invalid JSON arguments"
            else:
                if func_name == "frame_count":
                    tool_result = f"Total frames: {max_frames} (indices 0-{max_frames - 1})"
                elif func_name == "view_frames":
                    start = args.get("start", 0)
                    end = args.get("end", start)
                    resolution = args.get("resolution", "low")
                    max_w = 640 if resolution == "low" else 1280
                    q = 60 if resolution == "low" else 85
                    frames = _load_frames(frame_files, start, end, max_w, q)
                    if resolution == "low":
                        turns_low += len(frames)
                    else:
                        turns_high += len(frames)
                    tool_result = (
                        f"Returned {len(frames)} frame(s) [{start}-{end}] at {resolution} resolution."
                    )
                    # Append frames as a user message
                    img_content = [_build_image_content(f) for f in frames]
                    img_content.append({
                        "type": "text",
                        "text": f"Frames {start}-{end} at {resolution} resolution.",
                    })
                    messages.append({"role": "user", "content": img_content})
                else:
                    tool_result = f"Unknown tool: {func_name}"

            messages.append({
                "role": "tool",
                "tool_call_id": tc.id,
                "content": tool_result,
            })
    else:
        description = "Agentic failed: max turns (15) exceeded without final description"
        log.warning("Agentic: max turns exceeded for event=%s", event_id)

    # Agent summary — summarize the strategy/cost
    summary = None
    if description:
        summary = _summarize_agent(client, model, total_cost, turns_low, turns_high, turn + 1)
        if summary:
            description = f"{description}\n\n[{summary}]"

    # Persist full conversation log + summary
    try:
        AGENT_LOGS_DIR.mkdir(parents=True, exist_ok=True)
        log_path = AGENT_LOGS_DIR / f"{event_id}.json"
        _serializable = _serialize_for_log(messages, total_cost, event_id, camera, label,
                                           model, turn + 1, turns_low, turns_high, summary)
        log_path.write_text(_json.dumps(_serializable, default=str))
        log.info("Agentic log saved: %s", log_path)
        if summary:
            (AGENT_LOGS_DIR / f"{event_id}-summary.txt").write_text(summary)
    except Exception as e:
        log.warning("Failed to write agent log: %s", e)

    # Cost logged here (workflow.upsert_search_attributes can't be called
    # from activities — cost is in log file + agent summary instead).
    total_tokens = total_cost["prompt"] + total_cost["completion"]

    # Update stats
    _stats["model_counts"][model] = _stats["model_counts"].get(model, 0) + 1
    _stats["events_processed"] += 1
    _stats["last_event"] = f"{camera}/{label}/{event_id[:12]}"

    log.info("Agentic complete: %d turns, %d low/%d high, %d tokens, event=%s",
             turn + 1, turns_low, turns_high, total_tokens, event_id)
    return description


def _summarize_agent(
    client,
    model: str,
    total_cost: dict,
    turns_low: int,
    turns_high: int,
    num_turns: int,
) -> str | None:
    """Fire a second LLM call to summarize the agent's strategy."""
    prompt = (
        "Summarize the agent's frame-viewing strategy for this event in one sentence: "
        f"model used ({model}), how many frames were viewed ({turns_low} low-res, "
        f"{turns_high} high-res), how many turns it took ({num_turns}), and what it found. "
        "Mention the search pattern (e.g. binary search, linear scan, focused region)."
    )
    try:
        response = client.chat.completions.create(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            max_tokens=150,
        )
        summary = response.choices[0].message.content
        if summary:
            return f"Agent: {summary}"
    except Exception as e:
        log.warning("Agent summary call failed: %s", e)
    return None


def _serialize_for_log(
    messages: list,
    total_cost: dict,
    event_id: str,
    camera: str,
    label: str,
    model: str,
    num_turns: int,
    turns_low: int,
    turns_high: int,
    summary: str | None = None,
) -> dict:
    """Convert messages to a JSON-serializable structure with inline images."""
    import base64 as _b64
    result = {
        "event_id": event_id,
        "camera": camera,
        "label": label,
        "model": model,
        "turns": num_turns,
        "frames_viewed": {"low": turns_low, "high": turns_high},
        "total_cost": total_cost,
    }
    if summary:
        result["summary"] = summary

    serialized = []
    for m in messages:
        role = m.get("role", "unknown")
        entry = {"role": role}

        if "tool_calls" in m:
            entry["tool_calls"] = [
                {
                    "id": tc.get("id"),
                    "name": tc.get("function", {}).get("name", ""),
                    "arguments": tc.get("function", {}).get("arguments", ""),
                }
                for tc in m.get("tool_calls", [])
            ]
        elif "tool_call_id" in m:
            entry["tool_call_id"] = m.get("tool_call_id")
            entry["content"] = m.get("content", "")
        elif role == "assistant":
            entry["content"] = m.get("content", "")
        elif role == "user":
            content = m.get("content", "")
            if isinstance(content, list):
                parts = []
                for part in content:
                    if isinstance(part, dict) and part.get("type") == "image_url":
                        url = part.get("image_url", {}).get("url", "")
                        if url.startswith("data:"):
                            parts.append({"type": "image_url", "data": url})
                        else:
                            parts.append(part)
                    else:
                        parts.append(part)
                entry["content"] = parts
            else:
                entry["content"] = content
        else:
            entry["content"] = str(m.get("content", ""))

        serialized.append(entry)

    result["messages"] = serialized
    return result




@activity.defn(name="update_description")
async def update_description_activity(event_id: str, description: str) -> bool:
    """Update Frigate event description via API."""
    log.info("Activity update_description: event=%s", event_id)
    ok = await _run_with_heartbeat(update_event_description, event_id, description)
    if not ok:
        raise RuntimeError(f"Failed to update description for event {event_id}")
    return True


# ═════════════════════════════════════════════════════════════════════
# Temporal Workflow
# ═════════════════════════════════════════════════════════════════════

# Shared RetryPolicy — limits retries with backoff instead of infinite
_ACTIVITY_RETRY = RetryPolicy(
    maximum_attempts=3,
    initial_interval=timedelta(seconds=2),
    maximum_interval=timedelta(seconds=30),
    backoff_coefficient=2.0,
)
# Extract retry policy — polls for recording readiness up to ~180s
_EXTRACT_RETRY = RetryPolicy(
    maximum_attempts=12,
    initial_interval=timedelta(seconds=2),
    maximum_interval=timedelta(seconds=20),
    backoff_coefficient=2.0,
)

@workflow.defn
class GenAIWorkflow:
    """Orchestrates GenAI event processing: extract, genai, describe."""

    @workflow.run
    async def run(self, input_data: dict) -> None:
        event_id = input_data["event_id"]
        camera = input_data["camera"]
        label = input_data["label"]
        start_time = input_data["start_time"]
        end_time = input_data["end_time"]

        log_ctx = f"event={event_id} camera={camera} label={label}"

        workflow.logger.info("GenAI workflow started: %s", log_ctx)

        # Step 0: select model (car override is in input_data already)
        model = input_data.get("model")
        if model is None:
            model = await workflow.execute_activity(
                select_model_activity,
                input_data,
                start_to_close_timeout=timedelta(seconds=10),
                retry_policy=_ACTIVITY_RETRY,
            )
            input_data["model"] = model
        # Publish model as search attribute for filtering
        workflow.upsert_search_attributes([
            SearchAttributePair(_SEARCH_MODEL, model),
        ])
        workflow.logger.info("model=%s", model)

        skip_frames = input_data.get("skip_frames", False)

        # Step 1: fetch snapshot + extract ffmpeg frames (parallel)
        if skip_frames:
            frames_dir = await workflow.execute_activity(
                fetch_snapshot_activity,
                input_data,
                start_to_close_timeout=timedelta(seconds=30),
                retry_policy=_ACTIVITY_RETRY,
            )
        else:
            snapshot_dir, (ffmpeg_dir, frame_count) = await asyncio.gather(
                workflow.execute_activity(
                    fetch_snapshot_activity,
                    input_data,
                    start_to_close_timeout=timedelta(seconds=30),
                    retry_policy=_ACTIVITY_RETRY,
                ),
                workflow.execute_activity(
                    extract_frames_activity,
                    input_data,
                    task_queue=FFMPEG_TASK_QUEUE,
                    start_to_close_timeout=timedelta(seconds=60),
                    heartbeat_timeout=timedelta(seconds=10),
                    retry_policy=_EXTRACT_RETRY,
                ),
            )
            frames_dir = snapshot_dir

            # Upsert duration + frame count as search attributes
            dur_sec = int(end_time - start_time)
            workflow.upsert_search_attributes([
                SearchAttributePair(_SEARCH_DURATION, dur_sec),
            ])
            workflow.logger.info("duration=%ds frames=%d", dur_sec, frame_count)

            # Force Gemini when we have many frames (larger context window)
            if frame_count > 30:
                workflow.logger.info("frame_count=%d > 30 — forcing gemini", frame_count)
                input_data["model"] = "gemini/gemini-2.5-flash"

        # Step 2: progress patch
        await workflow.execute_activity(
            update_description_activity,
            args=[event_id, f"Processing {label} on {camera}..."],
            start_to_close_timeout=timedelta(seconds=15),
            retry_policy=_ACTIVITY_RETRY,
        )

        # Step 3: run GenAI (reads frames + snapshot from disk)
        # Route to model-specific task queue; pick activity based on agentic flag
        model = input_data.get("model", "gemini/gemini-2.5-flash")
        genai_queue = GEMINI_TASK_QUEUE if model.startswith("gemini/") else OLLAMA_TASK_QUEUE
        if input_data.get("agentic"):
            genai_activity = run_genai_agent_activity
        else:
            genai_activity = run_genai_activity
        description = await workflow.execute_activity(
            genai_activity,
            args=[input_data, frames_dir],
            task_queue=genai_queue,
            start_to_close_timeout=timedelta(seconds=600),
            heartbeat_timeout=timedelta(seconds=30),
            retry_policy=_ACTIVITY_RETRY,
        )

        # Step 4: final result
        if not description:
            workflow.logger.error("No description from GenAI: %s", log_ctx)
            await workflow.execute_activity(
                update_description_activity,
                args=[event_id, "Failed: GenAI returned no description"],
                start_to_close_timeout=timedelta(seconds=15),
                retry_policy=_ACTIVITY_RETRY,
            )
            return

        await workflow.execute_activity(
            update_description_activity,
            args=[event_id, description],
            start_to_close_timeout=timedelta(seconds=15),
            retry_policy=_ACTIVITY_RETRY,
        )

        workflow.logger.info("GenAI workflow completed: %s", log_ctx)


# ═════════════════════════════════════════════════════════════════════
# Temporal client reference & event loop (set by async_main)
# ═════════════════════════════════════════════════════════════════════

_temporal_client: Client | None = None
_main_event_loop: asyncio.AbstractEventLoop | None = None


# ── MQTT ────────────────────────────────────────────────────────────
# MQTT handler starts workflows directly via Temporal client (no queue).


def _start_workflow_sync(event: dict) -> None:
    """Schedule a Temporal workflow start from a non-async context (MQTT thread)."""
    event_id = event.get("id", "unknown")
    camera = event.get("camera", "")
    label = event.get("label", "")


    loop = _main_event_loop
    if loop is None:
        log.warning("Event loop not yet initialized, dropping event %s", event_id)
        return

    async def _start():
        client = _temporal_client
        if client is None:
            log.error("Temporal client not initialized, dropping event %s", event_id)
            return

        try:
            await client.start_workflow(
                "GenAIWorkflow",
                _build_workflow_input(event),
                id=f"genai-{event_id}",
                task_queue=TASK_QUEUE,
                search_attributes=TypedSearchAttributes([
                    SearchAttributePair(_SEARCH_CAMERA, camera),
                    SearchAttributePair(_SEARCH_LABEL, label),
                ]),
                memo={"event_id": event_id, "camera": camera, "label": label,
                      "duration": int(event.get("end_time", event.get("start_time", 0)) - event.get("start_time", 0))})
            log.info("Workflow started: genai-%s (%s/%s)", event_id, camera, label)
        except Exception as e:
            if "already" in str(e).lower() or "started" in str(e).lower():
                log.debug("Workflow genai-%s already exists (dedup)", event_id)
            else:
                log.exception("Failed to start workflow genai-%s", event_id)

    asyncio.run_coroutine_threadsafe(_start(), loop)


def _build_workflow_input(event: dict) -> dict:
    """Build the workflow input dict from an MQTT event. Model selection
    happens in the Temporal workflow via select_model_activity."""
    label = event.get("label", "")
    input_data = {
        "event_id": event["id"],
        "camera": event.get("camera", ""),
        "label": label,
        "start_time": event.get("start_time", 0),
        "end_time": event.get("end_time", event.get("start_time", 0)),
        "prompts_path": "/var/lib/frigate-genai-sidecar/prompts.json",
        "provider_path": "/var/lib/frigate-genai-sidecar/provider.json",
        "paused-ollama": os.path.exists("/tmp/pause-ollama"),
        "agentic": True,
    }
    # Cars: snapshot-only, gemini-only, make/model prompt
    if label == "car":
        input_data["skip_frames"] = True
        input_data["model"] = "gemini/gemini-2.5-flash"
    return input_data


def build_mqtt_client(loop: asyncio.AbstractEventLoop) -> mqtt.Client:
    """Create and configure the MQTT client. Starts workflows directly via Temporal."""

    def on_connect(client, userdata, flags, reason_code, properties=None):
        if reason_code == 0:
            log.info("MQTT connected, subscribing to frigate/events")
            _stats["mqtt_connected"] = True
            client.subscribe("frigate/events")
        else:
            log.error("MQTT connection failed: rc=%d", reason_code)

    def on_disconnect(client, userdata, flags, reason_code, properties=None):
        _stats["mqtt_connected"] = False
        if reason_code != 0:
            log.warning("MQTT disconnected: rc=%d", reason_code)

    def on_message(client, userdata, msg):
        log.debug("MQTT message on %s: %s", msg.topic, msg.payload[:200])
        try:
            payload = json.loads(msg.payload.decode())
            event_type = payload.get("type", "")
            after = payload.get("after", {})
            if not after.get("id"):
                return
            eid, camera, label = after["id"], after.get("camera"), after.get("label")

            if event_type == "end" and after.get("has_clip"):
                log.info("End event: %s (%s/%s)", eid, camera, label)
                _start_workflow_sync(after)

            elif event_type == "update":
                before = payload.get("before", {})
                def _desc(e):
                    return ((e.get("data") or {}).get("description") or e.get("description") or "").strip().lower()
                if _desc(after) == "redo" and _desc(before) != "redo":
                    after["has_clip"] = True
                    log.info("Redo trigger: %s (%s/%s)", eid, camera, label)
                    _start_workflow_sync(after)
        except json.JSONDecodeError:
            log.debug("Non-JSON MQTT message on %s", msg.topic)
        except Exception:
            log.exception("Error in MQTT message handler")

    mqtt_host = os.environ.get("MQTT_HOST", "localhost")
    mqtt_port = int(os.environ.get("MQTT_PORT", "1883"))
    mqtt_user = os.environ.get("MQTT_USER", "")
    mqtt_pass = os.environ.get("MQTT_PASSWORD", "")

    client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION2)
    if mqtt_user:
        client.username_pw_set(mqtt_user, mqtt_pass)
    client.on_connect = on_connect
    client.on_message = on_message
    client.on_disconnect = on_disconnect

    while True:
        try:
            client.connect(mqtt_host, mqtt_port, 60)
            break
        except Exception:
            log.warning("MQTT connection failed, retrying in 5s...")
            time.sleep(5)

    client.loop_start()
    return client


# ── main ────────────────────────────────────────────────────────────


async def async_main(prompts_path: str, provider_path: str) -> None:
    global _temporal_client, _main_event_loop

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(name)s] %(levelname)s: %(message)s",
    )
    _main_event_loop = asyncio.get_running_loop()

    prompts = load_json(prompts_path)
    provider_cfg = load_json(provider_path)

    describe_labels = prompts.get("describe", [])
    log.info("GenAI provider: %s / %s", provider_cfg.get("provider"), provider_cfg.get("model"))
    log.info("Describe labels: %s", ", ".join(sorted(describe_labels)))

    # ── Temporal client + worker ────────────────────────────────────
    temporal_address = os.environ.get("TEMPORAL_ADDRESS", "192.168.5.10:32682")
    log.info("Connecting to Temporal at %s", temporal_address)

    _temporal_client = await Client.connect(temporal_address, namespace="default")
    _stats["temporal_connected"] = True
    # Register search attributes for workflow filtering (idempotent)
    try:
        await _temporal_client.operator_service.add_search_attributes(
            AddSearchAttributesRequest(
                search_attributes={
                    "Camera": IndexedValueType.INDEXED_VALUE_TYPE_KEYWORD,
                    "Label": IndexedValueType.INDEXED_VALUE_TYPE_KEYWORD,
                    "EventId": IndexedValueType.INDEXED_VALUE_TYPE_KEYWORD,
                    "Duration": IndexedValueType.INDEXED_VALUE_TYPE_INT,
                    "Cost": IndexedValueType.INDEXED_VALUE_TYPE_INT,
                    "Model": IndexedValueType.INDEXED_VALUE_TYPE_KEYWORD,
                },
                namespace="default",
            ),
        )
        log.info("Search attributes registered: Camera, Label, EventId, Duration, Cost, Model")
    except Exception as e:
        log.debug("Search attribute registration skipped: %s", e)
    main_worker = Worker(
        _temporal_client,
        task_queue=TASK_QUEUE,
        workflows=[GenAIWorkflow],
        activities=[
            select_model_activity,
            update_description_activity,
            fetch_snapshot_activity,
        ],
    )

    # FFmpeg worker: frame extraction only (spiky CPU/disk, rate-limited)
    ffmpeg_worker = Worker(
        _temporal_client,
        task_queue=FFMPEG_TASK_QUEUE,
        activities=[extract_frames_activity],
        max_concurrent_activities=int(os.environ.get("TEMPORAL_MAX_FFMPEG", "3")),
    )

    # Gemini GenAI worker: handles both run_genai + run_genai_agent for gemini models
    gemini_worker = Worker(
        _temporal_client,
        task_queue=GEMINI_TASK_QUEUE,
        activities=[run_genai_activity, run_genai_agent_activity],
        max_concurrent_activities=int(os.environ.get("TEMPORAL_MAX_GEMINI_GENAI", "5")),
    )

    # Ollama GenAI worker: handles both run_genai + run_genai_agent for ollama models
    # Max 1 concurrent — Ollama cannot parallelize vision inference
    ollama_worker = Worker(
        _temporal_client,
        task_queue=OLLAMA_TASK_QUEUE,
        activities=[run_genai_activity, run_genai_agent_activity],
        max_concurrent_activities=int(os.environ.get("TEMPORAL_MAX_OLLAMA_GENAI", "1")),
    )

    main_task = asyncio.create_task(main_worker.run())
    ffmpeg_task = asyncio.create_task(ffmpeg_worker.run())
    gemini_task = asyncio.create_task(gemini_worker.run())
    ollama_task = asyncio.create_task(ollama_worker.run())
    log.info("Temporal workers started: %s + %s + %s + %s",
             TASK_QUEUE, FFMPEG_TASK_QUEUE, GEMINI_TASK_QUEUE, OLLAMA_TASK_QUEUE)

    # ── MQTT — starts workflows via Temporal client ─────────────────
    client_mqtt = build_mqtt_client(asyncio.get_running_loop())

    log.info("Frigate GenAI sidecar running, waiting for events...")

    # ── HTTP server for manual reprocess triggers ──────────────────
    import threading

    from http.server import HTTPServer, BaseHTTPRequestHandler

    async def _do_reprocess(event_id: str, event: dict) -> str:
        """Terminate old workflow and start a fresh one. Called via asyncio.run from HTTP handler."""
        workflow_id = f"genai-{event_id}"
        try:
            handle = _temporal_client.get_workflow_handle(workflow_id)
            await handle.terminate()
            log.info("Terminated old workflow %s for reprocess", workflow_id)
        except Exception:
            log.debug("No existing workflow %s to terminate", workflow_id)

        camera = event.get("camera", "")
        label = event.get("label", "")
        await _temporal_client.start_workflow(
            "GenAIWorkflow",
            _build_workflow_input(event),
            id=workflow_id,
            task_queue=TASK_QUEUE,
            search_attributes=TypedSearchAttributes([
                SearchAttributePair(_SEARCH_CAMERA, camera),
                SearchAttributePair(_SEARCH_LABEL, label),
            ]),
            memo={"event_id": event_id, "camera": camera, "label": label,
                  "duration": int(event.get("end_time", event.get("start_time", 0)) - event.get("start_time", 0))})
        return f"Reprocessing {event_id} ({event.get('camera', '')}/{event.get('label', '')})"

    class ReprocessHandler(BaseHTTPRequestHandler):
        def log_message(self, fmt, *args):
            log.debug("HTTP: %s", fmt % args)

        def _cors(self):
            self.send_header("Access-Control-Allow-Origin", "*")
            self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
            self.send_header("Access-Control-Allow-Headers", "Content-Type")

        def do_OPTIONS(self):
            self.send_response(200)
            self._cors()
            self.end_headers()

        def do_GET(self):
            if self.path == "/":
                self.send_response(200)
                self._cors()
                self.send_header("Content-type", "text/html; charset=utf-8")
                self.end_headers()
                self.wfile.write(UI_HTML.encode())
            elif self.path == "/api/stats":
                self.send_response(200)
                self._cors()
                self.send_header("Content-type", "application/json; charset=utf-8")
                self.end_headers()
                self.wfile.write(json.dumps(_stats).encode())
            elif self.path == "/api/temporal":
                self.send_response(200)
                self._cors()
                self.send_header("Content-type", "application/json; charset=utf-8")
                self.end_headers()
                self.wfile.write(json.dumps({
                    "connected": _stats["temporal_connected"],
                    "task_queue": TASK_QUEUE,
                    "server": os.environ.get("TEMPORAL_ADDRESS", "192.168.5.10:32682"),
                    "events_processed": _stats["events_processed"],
                    "model_counts": _stats["model_counts"],
                }).encode())
            elif self.path.startswith("/api/events/") and self.path.endswith("/snapshot.jpg"):
                self._proxy("image/jpeg")
            elif self.path.startswith("/api/events"):
                self._proxy("application/json")
            elif self.path == "/api/pause":
                paused = os.path.exists("/tmp/pause-ollama")
                self.send_response(200)
                self._cors()
                self.send_header("Content-type", "application/json")
                self.end_headers()
                self.wfile.write(json.dumps({"paused": paused}).encode())
            else:
                self.send_response(404)
                self.end_headers()

        def _proxy(self, content_type):
            base_url = os.environ.get("FRIGATE_BASE_URL", "http://localhost:5000")
            try:
                resp = urllib.request.urlopen(base_url + self.path, timeout=15)
                self.send_response(resp.status)
                self._cors()
                self.send_header("Content-type", content_type)
                self.end_headers()
                self.wfile.write(resp.read())
            except Exception as e:
                self.send_response(502)
                self._cors()
                self.end_headers()
                self.wfile.write(str(e).encode())
        def do_POST(self):
            if self.path.startswith("/reprocess/"):
                event_id = self.path.split("/reprocess/", 1)[1]
                base_url = os.environ.get("FRIGATE_BASE_URL", "http://localhost:5000")
                try:
                    resp = urllib.request.urlopen(f"{base_url}/api/events/{event_id}", timeout=10)
                    event = json.loads(resp.read())

                    if _temporal_client is None:
                        self.send_response(503)
                        self._cors()
                        self.send_header("Content-type", "text/plain")
                        self.end_headers()
                        self.wfile.write(b"Temporal not connected")
                        return

                    msg = asyncio.run(_do_reprocess(event_id, event))

                    self.send_response(200)
                    self._cors()
                    self.send_header("Content-type", "text/plain")
                    self.end_headers()
                    self.wfile.write(msg.encode())
                    log.info("HTTP reprocess: %s", msg)
                except Exception as e:
                    self.send_response(500)
                    self._cors()
                    self.end_headers()
                    self.wfile.write(str(e).encode())
                    log.error("Reprocess failed: %s", e)

            elif self.path == "/api/pause":
                pause_file = "/tmp/pause-ollama"
                if os.path.exists(pause_file):
                    os.remove(pause_file)
                    paused = False
                else:
                    open(pause_file, "w").close()
                    paused = True
                self.send_response(200)
                self._cors()
                self.send_header("Content-type", "application/json")
                self.end_headers()
                self.wfile.write(json.dumps({"paused": paused}).encode())
                log.info("Ollama pause toggled: %s", "ON" if paused else "OFF")
            else:
                self.send_response(404)
                self.end_headers()

    http_port = int(os.environ.get("HTTP_PORT", "9090"))
    http_host = os.environ.get("HTTP_HOST", "127.0.0.1")
    httpd = HTTPServer((http_host, http_port), ReprocessHandler)
    thread = threading.Thread(target=httpd.serve_forever, daemon=True)
    thread.start()
    log.info("HTTP reprocess endpoint on http://%s:%d", http_host, http_port)

    # ── Run workers (block forever; crash propagates, systemd restarts)
    try:
        await asyncio.gather(main_task, ffmpeg_task)
    finally:
        client_mqtt.loop_stop()
        client_mqtt.disconnect()


def main():
    parser = argparse.ArgumentParser(description="Frigate GenAI Sidecar")
    parser.add_argument(
        "--prompts", default="/var/lib/frigate-genai-sidecar/prompts.json",
        help="Path to prompts JSON file",
    )
    parser.add_argument(
        "--provider", default="/var/lib/frigate-genai-sidecar/provider.json",
        help="Path to provider JSON file",
    )
    args = parser.parse_args()
    asyncio.run(async_main(args.prompts, args.provider))


if __name__ == "__main__":
    main()
