#!/usr/bin/env python3
"""
Frigate GenAI sidecar — multi-frame event descriptions via Gemini/LiteLLM/Ollama.

Listens to MQTT for completed Frigate events, extracts full frames from
recordings at adaptive FPS, sends them to a vision LLM with a composed
prompt, and writes the description back to Frigate.

Configuration read from two JSON files (generated by Nix):
  /var/lib/frigate-genai-sidecar/prompts.json
  /var/lib/frigate-genai-sidecar/provider.json

Environment:
  FRIGATE_BASE_URL  — Frigate HTTP API (default: http://localhost:5000)
  MQTT_HOST         — MQTT broker (default: localhost)
  MQTT_PORT         — MQTT port (default: 1883)
"""

import argparse
import asyncio
import json
import logging
import math
import os
import queue
import subprocess
import sys
import tempfile
import time
import urllib.request
from pathlib import Path

import paho.mqtt.client as mqtt

log = logging.getLogger("frigate-genai-sidecar")


# ── config ──────────────────────────────────────────────────────────

def load_json(path: str) -> dict:
    with open(path) as f:
        return json.load(f)


# ── frame extraction ────────────────────────────────────────────────

def extract_frames(
    camera: str,
    start_time: float,
    end_time: float,
    fps: float,
    max_frames: int = 30,
    max_width: int = 1280,
    jpg_quality: int = 85,
) -> list[bytes]:
    """
    Extract JPEG frames from Frigate recording via HLS.

    Returns list of JPEG byte strings, chronologically ordered.
    """
    base_url = os.environ.get("FRIGATE_BASE_URL", "http://localhost:5000")
    # Frigate VOD endpoint: /vod/<camera>/start/<ts>/end/<ts>/index.m3u8
    hls_url = (
        f"{base_url}/vod/{camera}"
        f"/start/{int(start_time)}/end/{int(math.ceil(end_time))}"
        f"/index.m3u8"
    )
    duration = end_time - start_time

    log.info(
        "Extracting up to %d frames at %.1ffps from %s (%.1fs clip)",
        max_frames, fps, hls_url, duration,
    )

    with tempfile.TemporaryDirectory(prefix="frigate-genai-") as tmp:
        cmd = [
            "ffmpeg",
            "-y",
            "-loglevel", "error",
            "-i", hls_url,
            "-vf", f"fps={fps},scale=1280:-2",
            "-frames:v", str(max_frames),
            "-q:v", str(max(1, min(31, int(31 - 31 * jpg_quality / 100)))),
            f"{tmp}/frame_%03d.jpg",
        ]
        try:
            subprocess.run(cmd, check=True, timeout=60)
        except subprocess.CalledProcessError as e:
            log.error("ffmpeg failed: %s", e)
            return []
        except subprocess.TimeoutExpired:
            log.error("ffmpeg timed out extracting frames")
            return []

        # Collect frames in order
        frames = []
        for p in sorted(Path(tmp).glob("frame_*.jpg")):
            frames.append(p.read_bytes())

        if not frames:
            log.warning("No frames extracted")
        else:
            log.info("Extracted %d frames", len(frames))

        return frames


def fetch_snapshot(event_id: str) -> bytes | None:
    """Fetch the event snapshot (close-up of tracked object)."""
    base_url = os.environ.get("FRIGATE_BASE_URL", "http://localhost:5000")
    url = f"{base_url}/api/events/{event_id}/snapshot.jpg"
    try:
        req = urllib.request.Request(url)
        with urllib.request.urlopen(req, timeout=15) as resp:
            return resp.read()
    except Exception as e:
        log.warning("Failed to fetch snapshot for %s: %s", event_id, e)
        return None


# ── Gemini provider ─────────────────────────────────────────────────

def call_gemini(
    prompt_text: str,
    images: list[bytes],
    snapshot: bytes | None,
    label: str,
    provider_cfg: dict,
) -> str | None:
    """
    Call Gemini 2.5 Flash with sequential contents:
      [prompt_text, frame1...frameN, transition_text, snapshot]
    """
    from google import genai
    from google.genai import types

    api_key = os.environ.get(provider_cfg.get("api_key_env", ""), "")
    if not api_key:
        log.error("Gemini API key not found in env var %s", provider_cfg.get("api_key_env"))
        return None

    client = genai.Client(api_key=api_key)

    contents: list = [prompt_text]

    # Add all frames as image parts
    for img in images:
        contents.append(types.Part.from_bytes(data=img, mime_type="image/jpeg"))

    # Add snapshot as detail close-up with transition text
    if snapshot:
        contents.append(
            f"The next image is a close-up of the {label}. "
            "Use it for appearance detail (clothing, items, expression); "
            "use the preceding full frames for scene context, movement, "
            "and event progression."
        )
        contents.append(types.Part.from_bytes(data=snapshot, mime_type="image/jpeg"))

    log.info("Calling %s with %d images + 1 snapshot", provider_cfg["model"], len(images))

    try:
        response = client.models.generate_content(
            model=provider_cfg["model"],
            contents=contents,
        )
        return response.text
    except Exception as e:
        log.error("Gemini call failed: %s", e)
        return None


# ── provider dispatch ───────────────────────────────────────────────

PROVIDERS = {
    "gemini": call_gemini,
}


def call_provider(
    prompt_text: str,
    images: list[bytes],
    snapshot: bytes | None,
    label: str,
    provider_cfg: dict,
) -> str | None:
    """Dispatch to the configured GenAI provider."""
    provider_name = provider_cfg.get("provider", "gemini")
    fn = PROVIDERS.get(provider_name)
    if fn is None:
        log.error("Unknown provider: %s", provider_name)
        return None
    return fn(prompt_text, images, snapshot, label, provider_cfg)


# ── Frigate API ─────────────────────────────────────────────────────

def update_event_description(event_id: str, description: str) -> bool:
    """Write description back to Frigate's event."""
    base_url = os.environ.get("FRIGATE_BASE_URL", "http://localhost:5000")
    url = f"{base_url}/api/events/{event_id}"
    payload = json.dumps({"description": description}).encode()
    try:
        req = urllib.request.Request(
            url, data=payload, method="PUT",
            headers={"Content-Type": "application/json"},
        )
        with urllib.request.urlopen(req, timeout=10) as resp:
            return resp.status == 200
    except Exception as e:
        log.error("Failed to update event %s: %s", event_id, e)
        return False


# ── prompt composition ──────────────────────────────────────────────

def compose_prompt(
    prompts: dict,
    camera: str,
    label: str,
    num_frames: int,
) -> str:
    """Compose the prompt from the Nix-generated template blocks."""
    base = prompts.get("base", "")
    camera_desc = prompts.get("camera", {}).get(camera, "")
    suffix = prompts.get("suffix", "")
    # Use object-specific hint if available, otherwise the label-specific prompt
    label_hint = prompts.get("label", {}).get(label, "")

    # Replace {label} placeholder in base
    base = base.replace("{label}", label)

    parts = [base]
    if camera_desc:
        parts.append(camera_desc)
    if label_hint:
        parts.append(label_hint)
    if suffix:
        parts.append(suffix)

    prompt = " ".join(parts)
    # Replace {label} in the assembled prompt too (suffix/camera may use it)
    prompt = prompt.replace("{label}", label)
    # Add frame count
    # Replace the "count frames" debug directive with actual frame info
    first_line = "FIRST: State exactly how many image frames you received."
    if first_line in prompt:
        prompt = prompt.replace(
            first_line,
            f"You are viewing {num_frames} chronological frames from a security camera, "
            f"at ~1-4 frames per second, plus one close-up detail image",
        )

    return prompt


# ── event processing ────────────────────────────────────────────────

class EventProcessor:
    """Processes Frigate events: extract frames, call GenAI, update description."""

    def __init__(self, prompts: dict, provider_cfg: dict):
        self.prompts = prompts
        self.provider_cfg = provider_cfg
        self.describe_labels: set[str] = set(prompts.get("describe", []))
        # Per-camera lock: only one active request per camera
        self._camera_busy: dict[str, bool] = {}

    async def process(self, event: dict) -> None:
        """Process a single event (called from asyncio main loop)."""
        event_id = event.get("id")
        camera = event.get("camera", "")
        label = event.get("label", "")
        start_time = event.get("start_time", 0)
        end_time = event.get("end_time", start_time)
        has_clip = event.get("has_clip", False)

        # ── filters ──
        if not has_clip:
            log.debug("Event %s has no clip, skipping", event_id)
            return
        if not end_time:
            log.debug("Event %s has no end_time, skipping", event_id)
            return
        if label not in self.describe_labels:
            log.debug("Event %s label=%s not in describe list, skipping", event_id, label)
            return

        # ── rate-limit per camera ──
        if self._camera_busy.get(camera):
            log.info("Camera %s busy, skipping event %s", camera, event_id)
            return
        self._camera_busy[camera] = True

        try:
            await self._process_event(event_id, camera, label, start_time, end_time)
        finally:
            self._camera_busy[camera] = False

    async def _process_event(
        self,
        event_id: str,
        camera: str,
        label: str,
        start_time: float,
        end_time: float,
    ) -> None:
        duration = end_time - start_time
        fps = max(1, min(4, 4 / max(1, duration)))
        max_frames = max(4, min(30, int(duration * fps)))

        log.info(
            "Processing event %s: camera=%s label=%s duration=%.1fs frames=%d fps=%.1f",
            event_id, camera, label, duration, max_frames, fps,
        )

        # 0. Brief delay for Frigate to finalize recording segments
        await asyncio.sleep(2)

        # 1. Extract frames from recording
        start_ts = time.monotonic()
        frames = await asyncio.to_thread(
            extract_frames, camera, start_time, end_time, fps, max_frames,
        )
        extract_time = time.monotonic() - start_ts
        log.info("Frame extraction took %.1fs", extract_time)

        if not frames:
            log.error("No frames extracted for event %s", event_id)
            return

        # 2. Fetch snapshot (close-up detail)
        snapshot = await asyncio.to_thread(fetch_snapshot, event_id)

        # 3. Compose prompt
        prompt = compose_prompt(self.prompts, camera, label, len(frames))

        # 4. Call GenAI provider
        genai_start = time.monotonic()
        description = await asyncio.to_thread(
            call_provider, prompt, frames, snapshot, label, self.provider_cfg,
        )
        genai_time = time.monotonic() - genai_start
        log.info("GenAI call took %.1fs", genai_time)

        if not description:
            log.error("No description returned for event %s", event_id)
            return

        # 5. Write description to Frigate
        ok = await asyncio.to_thread(update_event_description, event_id, description)
        if ok:
            log.info(
                "Updated event %s (%s/%s) — %.1fs total",
                event_id, camera, label,
                time.monotonic() - start_ts,
            )
        else:
            log.error("Failed to update event %s", event_id)


# ── MQTT ────────────────────────────────────────────────────────────

def build_mqtt_client(processor: EventProcessor, event_queue: asyncio.Queue) -> mqtt.Client:
    """Create and configure the MQTT client with event callback."""

    def on_connect(client, userdata, flags, reason_code, properties=None):
        if reason_code == 0:
            log.info("MQTT connected, subscribing to frigate/events")
            client.subscribe("frigate/events")
        else:
            log.error("MQTT connection failed: rc=%d", reason_code)

    def on_message(client, userdata, msg):
        try:
            payload = json.loads(msg.payload.decode())
            event_type = payload.get("type", "")
            if event_type == "end":
                after = payload.get("after", {})
                if after.get("has_clip"):
                    # Put in queue for async processing
                    try:
                        event_queue.put_nowait(after)
                    except asyncio.QueueFull:
                        log.warning("Event queue full, dropping event %s", after.get("id"))
        except json.JSONDecodeError:
            log.debug("Non-JSON MQTT message on %s", msg.topic)
        except Exception:
            log.exception("Error in MQTT message handler")

    mqtt_host = os.environ.get("MQTT_HOST", "localhost")
    mqtt_port = int(os.environ.get("MQTT_PORT", "1883"))
    mqtt_user = os.environ.get("MQTT_USER", "")
    mqtt_pass = os.environ.get("MQTT_PASSWORD", "")

    client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION2)
    if mqtt_user:
        client.username_pw_set(mqtt_user, mqtt_pass)
    client.on_connect = on_connect
    client.on_message = on_message

    # Retry connection
    while True:
        try:
            client.connect(mqtt_host, mqtt_port, 60)
            break
        except Exception:
            log.warning("MQTT connection failed, retrying in 5s...")
            time.sleep(5)

    client.loop_start()
    return client


# ── main ────────────────────────────────────────────────────────────

async def async_main(prompts_path: str, provider_path: str) -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(name)s] %(levelname)s: %(message)s",
    )

    prompts = load_json(prompts_path)
    provider_cfg = load_json(provider_path)

    log.info("GenAI provider: %s / %s", provider_cfg.get("provider"), provider_cfg.get("model"))
    log.info("Describe labels: %s", ", ".join(sorted(prompts.get("describe", []))))

    processor = EventProcessor(prompts, provider_cfg)
    event_queue: asyncio.Queue = asyncio.Queue(maxsize=100)

    # Start MQTT in background thread
    client = build_mqtt_client(processor, event_queue)

    log.info("Frigate GenAI sidecar running, waiting for events...")

    try:
        while True:
            event = await event_queue.get()
            try:
                await processor.process(event)
            except Exception:
                log.exception("Error processing event %s", event.get("id"))
    finally:
        client.loop_stop()
        client.disconnect()


def main():
    parser = argparse.ArgumentParser(description="Frigate GenAI Sidecar")
    parser.add_argument(
        "--prompts", default="/var/lib/frigate-genai-sidecar/prompts.json",
        help="Path to prompts JSON file",
    )
    parser.add_argument(
        "--provider", default="/var/lib/frigate-genai-sidecar/provider.json",
        help="Path to provider JSON file",
    )
    args = parser.parse_args()
    asyncio.run(async_main(args.prompts, args.provider))


if __name__ == "__main__":
    main()
