[package]
name = "binder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
home = "0.5.4"
anyhow = "1.0.70"
regex = "1.8.1"
